package org.villageastra.client;
import net.minecraft.client.Minecraft;
import net.minecraft.client.Screenshot;
import net.minecraft.nbt.*;
import net.minecraft.world.item.ItemStack;
import org.villageastra.VillageAstra;
import org.villageastra.domain.*;
import org.villageastra.server.*;
import org.villageastra.world.*;
/** Real mayor GUI packets, scientist work consumption, target switching and reload (AD-136: level-II nodes of 7 works). */
final class ResearchGraphProbe {
 private static int phase,ticks;private static volatile boolean supplied,done;private static volatile String failure;private static boolean stopped;
 static boolean enabled(){return Boolean.getBoolean("villageastra.researchGraphSmoke");}
 private static ResidentEntity worker(net.minecraft.server.MinecraftServer s,SettlementData.Entry e,Profession role){return (ResidentEntity)s.overworld().getEntity(e.settlement().residents().stream().filter(r->r.profession()==role).findFirst().orElseThrow().id());}
 static void setup(net.minecraft.server.MinecraftServer s){ScienceProbe.setup(s);var e=SettlementData.get(s).entries().iterator().next();e.settlement().appointPlayerMayor(s.getPlayerList().getPlayers().get(0).getUUID());worker(s,e,Profession.SCIENTIST).setNoAi(true);var lab=e.settlement().buildings().stream().filter(b->b.type().equals("laboratory")).findFirst().orElseThrow();var c=LogisticsRoutes.chest(s.overworld(),e,lab);c.clearContent();c.setItem(0,new ItemStack(VillageAstra.RESEARCH_VOLUME.get(),2));var hall=e.settlement().buildings().stream().filter(b->b.type().equals("town_hall")).findFirst().orElseThrow();LogisticsRoutes.chest(s.overworld(),e,hall).setItem(25,new ItemStack(VillageAstra.RESEARCH_VOLUME.get(),14));
  // AD-136: level I is paid in resources, so the books buy level-II nodes: the village has Science I and Agriculture I and a hall of level II.
  var record=BookResearch.inspect(s.overworld(),e);var done=record.getList("legacyDone",net.minecraft.nbt.Tag.TAG_STRING);for(var id:java.util.List.of("research.1","agriculture.1"))done.add(net.minecraft.nbt.StringTag.valueOf(id));record.put("legacyDone",done);BookResearch.store(s.overworld(),e,record);
  if(e.settlement().civilization().level()<2)e.settlement().civilization().completedHallUpgrade(2);SettlementData.get(s).setDirty();}
 private static void require(boolean ok,String why){if(!ok)throw new IllegalStateException(why);}
 private static void call(Minecraft mc,java.util.function.Consumer<net.minecraft.server.MinecraftServer> action){mc.getSingleplayerServer().execute(()->{try{action.accept(mc.getSingleplayerServer());}catch(Exception ex){failure=ex.toString();}});}
 private static void click(Minecraft mc,double x,double y){mc.screen.tick();require(mc.screen.mouseClicked(x,y,0),"Inactive research GUI control");mc.screen.mouseReleased(x,y,0);}
 /** The office opened on its Science tab: the tree replaces the office on its first tick, as it does for a player. */
 private static void open(Minecraft mc){OfficeProbes.open(mc,ConstructionScreen.RESEARCH);mc.screen.tick();require(mc.screen instanceof ResearchScreen,"The science tab did not open the research tree");}
 private static void select(Minecraft mc,String id){open(mc);var tree=((ResearchScreen)mc.screen).panel();tree.search().setValue(id);var frame=tree.frameCenter(id);click(mc,frame[0],frame[1]);require(tree.selected().equals(id),"The tree frame did not select "+id);mc.screen.tick();OfficeProbes.clickOrFail(mc.screen,tree.choose(),"The choose-target button");}
 static void tick(Minecraft mc){if(stopped)return;try{if(failure!=null)throw new IllegalStateException(failure);if(++ticks>6000)throw new IllegalStateException("Research graph timeout phase="+phase);var t=ConstructionOverlay.snapshot();var r=t.getCompound("research");boolean reload=Boolean.getBoolean("villageastra.reloadSmoke");if(ticks%200==0)com.mojang.logging.LogUtils.getLogger().info("ASTRA_RESEARCH_GRAPH phase={} selected={} paid={}",phase,r.getString("selected"),r.getCompound("paid"));
  if(phase==0&&t.getBoolean("canManage")&&t.contains("research")){if(reload){open(mc);phase=7;}else{select(mc,"research.2");phase=1;}}
  else if(phase==1&&r.getString("selected").equals("research.2")){call(mc,s->{var e=SettlementData.get(s).entries().iterator().next();worker(s,e,Profession.SCIENTIST).setNoAi(false);});phase=2;}
  else if(phase==2&&r.getCompound("paid").getInt("research.2")==2){call(mc,s->{var e=SettlementData.get(s).entries().iterator().next();worker(s,e,Profession.SCIENTIST).setNoAi(true);});select(mc,"agriculture.2");phase=3;}
  else if(phase==3&&r.getString("selected").equals("agriculture.2")){call(mc,s->{var e=SettlementData.get(s).entries().iterator().next();worker(s,e,Profession.PORTER).setNoAi(false);});phase=4;}
  else if(phase==4){if(ticks%10==0)call(mc,s->{var e=SettlementData.get(s).entries().iterator().next();var lab=e.settlement().buildings().stream().filter(b->b.type().equals("laboratory")).findFirst().orElseThrow();if(LogisticsRoutes.chest(s.overworld(),e,lab).countItem(VillageAstra.RESEARCH_VOLUME.get())>=7){worker(s,e,Profession.SCIENTIST).setNoAi(false);supplied=true;}});if(supplied){phase=5;}}
  else if(phase==5&&r.getCompound("paid").getInt("agriculture.2")>0){require(r.getCompound("paid").getInt("agriculture.2")<7,"Expected an unfinished alternate target");call(mc,s->{var e=SettlementData.get(s).entries().iterator().next();worker(s,e,Profession.SCIENTIST).setNoAi(true);});select(mc,"research.2");phase=6;}
  else if(phase==6&&r.getString("selected").equals("research.2")){call(mc,s->{var e=SettlementData.get(s).entries().iterator().next();worker(s,e,Profession.SCIENTIST).setNoAi(false);});phase=7;}
  else if(phase==7&&r.getCompound("paid").getInt("research.2")==7){if(ticks%10==0)call(mc,s->{var e=SettlementData.get(s).entries().iterator().next();var l=s.overworld();var record=BookResearch.inspect(l,e);int partial=record.getCompound("paid").getInt("agriculture.2");require(partial>0&&partial<7&&BookResearch.completed(e,record).contains("research.2"),"Lost invested progress or completed technology");if(PorterWork.active(PorterWork.inspect(l,worker(s,e,Profession.PORTER).getUUID())))return;int stock=0;for(var b:e.settlement().buildings()){var c=LogisticsRoutes.chest(l,e,b);if(c!=null)stock+=c.countItem(VillageAstra.RESEARCH_VOLUME.get());}require(stock+7+partial==16,"Book conservation failed");worker(s,e,Profession.SCIENTIST).setNoAi(true);worker(s,e,Profession.PORTER).setNoAi(true);done=true;});if(done){open(mc);phase=8;ticks=0;}}
  else if(phase==8&&ticks>40){stopped=true;var path=java.nio.file.Path.of("../docs/runs/"+mc.getSingleplayerServer().getWorldPath(net.minecraft.world.level.storage.LevelResource.ROOT).normalize().getFileName()+"-research-graph.png");try(var image=Screenshot.takeScreenshot(mc.getMainRenderTarget())){image.writeToFile(path);}com.mojang.logging.LogUtils.getLogger().info("ASTRA_RESEARCH_GRAPH screenshot {}",path);com.mojang.logging.LogUtils.getLogger().info("ASTRA_RESEARCH_GRAPH layout {}",OfficeProbes.layoutProblems(mc.screen));call(mc,s->{s.saveEverything(false,true,true);com.mojang.logging.LogUtils.getLogger().info("ASTRA_RESEARCH_GRAPH VERIFIED actual GUI search, mayor target selection, physical books, target switching preserves investment, seven books unlock catalog; reload={}",reload);mc.execute(mc::stop);});}
 }catch(Exception ex){stopped=true;com.mojang.logging.LogUtils.getLogger().error("ASTRA_RESEARCH_GRAPH FAILED",ex);mc.stop();}}
}
