package org.villageastra.gametest;
import java.util.*;
import net.minecraft.core.BlockPos;
import net.minecraft.core.registries.*;
import net.minecraft.gametest.framework.*;
import net.minecraft.nbt.*;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.tags.TagKey;
import net.minecraft.world.item.*;
import net.minecraft.world.level.block.Blocks;
import net.minecraftforge.gametest.*;
import org.villageastra.VillageAstra;
import org.villageastra.domain.*;
import org.villageastra.server.*;
import org.villageastra.world.*;
import org.villageastra.persistence.*;
/** AD471: the labor office fills the existing scientific seats; clock services remain full-price fixtures. */
@GameTestHolder(VillageAstra.ID) @PrefixGameTestTemplate(false)
public final class AutonomousScienceStaffingGameTests {
 private static int serial;
 private static final long W=ScienceBalance.WORK_TICKS;
 private record Town(net.minecraft.server.level.ServerLevel l,SettlementData.Entry e,Settlement s,Settlement.Building hall,Settlement.Building lab,List<net.minecraft.world.level.ChunkPos> held){
  Settlement.Building kept(){return s.buildings().stream().filter(b->b.id().equals(lab.id())).findFirst().orElseThrow();}
  void close(){for(var r:s.residents())if(l.getEntity(r.id()) instanceof ResidentEntity body)body.discard();SettlementData.get(l.getServer()).remove(s.id());BuildingLevels.forgetBest(s.id());BookResearch.clearCache();PhysicalFixtureChunks.release(l,held);}
 }
 private static Resident resident(Town t,boolean educated){var r=new Resident(UUID.randomUUID(),Resident.Life.ADULT,educated,null,null,-1);t.s.admit(r,t.s.homes().iterator().next().id());return r;}
 private static Town town(GameTestHelper h){
  var l=h.getLevel();var at=h.absolutePos(BlockPos.ZERO);var center=new BlockPos(at.getX()+3670016+(serial++)*128,110,at.getZ());var held=PhysicalFixtureChunks.force(l,center,-3,62,-3,18);for(var c:held)l.getChunk(c.x,c.z);for(var p:BlockPos.betweenClosed(center.offset(-3,-1,-3),center.offset(62,18,18)))l.setBlock(p,p.getY()<center.getY()?Blocks.STONE.defaultBlockState():Blocks.AIR.defaultBlockState(),2);
  var s=new Settlement(UUID.randomUUID());var hall=new Settlement.Building(UUID.randomUUID(),"town_hall",0,0,0);var lab=new Settlement.Building(UUID.randomUUID(),"laboratory",30,0,0);s.addBuilding(hall);s.addBuilding(lab);s.addHome(new Settlement.Home(UUID.randomUUID(),1,32,true));var e=new SettlementData.Entry(s,l.dimension().location().toString(),center);SettlementData.get(l.getServer()).add(e);ResearchV2Town.lay(l,e,hall,"town_hall");ResearchV2Town.lay(l,e,lab,"laboratory");var t=new Town(l,e,s,hall,lab,held);var builder=resident(t,false);s.assign(builder.id(),Profession.BUILDER,hall.id());var porter=resident(t,false);s.assign(porter.id(),Profession.PORTER,hall.id());var scientist=resident(t,true);s.assign(scientist.id(),Profession.SCIENTIST,lab.id());BookResearch.clearCache();return t;
 }
 private static long paidLabTwo(GameTestHelper h,Town t){
  var node=ResearchCatalog.get("research.1");var stock=LogisticsRoutes.chest(t.l,t.e,t.hall);stock.clearContent();int slot=0;for(var c:node.resources()){var item=c.tag()==null?BuiltInRegistries.ITEM.get(new ResourceLocation(c.item())):BuiltInRegistries.ITEM.getTagOrEmpty(TagKey.create(Registries.ITEM,new ResourceLocation(c.tag()))).iterator().next().value();stock.setItem(slot++,new ItemStack(item,c.count()));}h.assertTrue(BookResearch.payResources(t.l,t.e,node.id())&&stock.isEmpty(),"Science I is really paid in the full published resources");
  h.assertTrue(BookResearch.autoSelect(t.l,t.e).equals("town_hall.2"),"Actual next-hall exception opens the bootstrap scientific target");long now=0;h.assertTrue(ScienceWorks.advance(t.l,t.e,now)==0,"Initial science grants no books");now=spend(h,t,"town_hall.2",now);t.s.civilization().completedHallUpgrade(2);ResearchV2Town.lay(t.l,t.e,t.hall,BuildingTiers.layoutId("town_hall",2));BuildingLevels.forgetBest(t.s.id());h.assertTrue(BookResearch.autoSelect(t.l,t.e).equals("research.2"),"Actual NPC selects Science II after the independent initial hall-II fixture stands");now=spend(h,t,"research.2",now);t.s.raiseBuildingLevel(t.lab.id(),2);ResearchV2Town.lay(t.l,t.e,t.kept(),BuildingTiers.layoutId("laboratory",2));BuildingLevels.forgetBest(t.s.id());
  h.assertTrue(LogisticsRoutes.chest(t.l,t.e,t.kept())!=null&&BuildingTiers.level(t.l,t.e,t.kept())==2&&ScienceWorks.places(t.l,t.e)==2&&BookResearch.inspect(t.l,t.e).getList("legacyDone",Tag.TAG_STRING).isEmpty()&&ResearchGate.has(t.l,t.e,"research.2"),"Physical lab-II core and equipment stand with seven actually paid works and no legacy knowledge grants");return now;
 }
 private static long spend(GameTestHelper h,Town t,String id,long now){int works=ResearchCatalog.get(id).works();h.assertTrue(ScienceWorks.advance(t.l,t.e,now+works*W)==works,"Every scientific work takes its full unchanged WORK_TICKS period");for(int i=0;i<works;i++)h.assertTrue(BookResearch.consume(t.l,t.e,t.kept()),"Actual research consumes produced work "+i);h.assertTrue(ResearchGate.has(t.l,t.e,id)&&LogisticsRoutes.chest(t.l,t.e,t.kept()).countItem(VillageAstra.RESEARCH_VOLUME.get())==0,"All produced works are spent exactly once");return now+works*W;}
 private static long scientists(Town t){return t.s.residents().stream().filter(r->r.alive()&&r.profession()==Profession.SCIENTIST&&t.kept().equals(t.s.workplace(r.id()))).count();}
 @GameTest(template="empty",batch="science_staffing_baseline",timeoutTicks=200)
 public static void theActualLaborOfficeFillsTheSecondPaidPhysicalScientificSeat(GameTestHelper h){
  var t=town(h);try{paidLabTwo(h,t);var candidate=resident(t,true);var extra=resident(t,true);Population.assign(t.l,t.e,1);for(int i=0;i<10;i++)Population.assign(t.l,t.e,1);long staffed=scientists(t);com.mojang.logging.LogUtils.getLogger().info("ZIMBOVILLAGERS_SCIENCE_STAFFING paidResearchTwo={} workingPlaces={} actualScientists={} idle={} actualServerTick={}",BookResearch.inspect(t.l,t.e).getCompound("paid").getInt("research.2"),ScienceWorks.places(t.l,t.e),staffed,t.s.residents().stream().filter(r->r.profession()==null).count(),t.l.getServer().getTickCount());h.assertTrue(staffed==2,"Actual labor office must fill both paid physical scientific seats, observed="+staffed);h.assertTrue(candidate.profession()==Profession.SCIENTIST&&extra.profession()==null,"Only the one remaining scientific vacancy is filled, without inventing another post");}finally{t.close();}h.succeed();
 }

 @GameTest(template="empty",batch="science_staffing_levels",timeoutTicks=200)
 public static void autonomousScientistPostsFollowAllSixExistingKeptLevels(GameTestHelper h){
  var t=town(h);try{for(int i=0;i<8;i++)resident(t,true);for(int level=1;level<=6;level++){if(level>1)t.s.raiseBuildingLevel(t.lab.id(),level);ResearchV2Town.lay(t.l,t.e,t.kept(),BuildingTiers.layoutId("laboratory",level));BuildingLevels.forgetBest(t.s.id());Population.assign(t.l,t.e,1);Population.assign(t.l,t.e,1);ScienceWorks.advance(t.l,t.e,1000+level*20);h.assertTrue(Population.slots(t.s,t.kept())==ScienceBalance.seats(level)&&scientists(t)==ScienceBalance.seats(level)&&ScienceWorks.places(t.l,t.e)==ScienceBalance.seats(level)&&ScienceWorks.seated(t.l,t.e)==ScienceBalance.seats(level),"Kept staffing and physically working seats follow the existing tier "+level+" table");}
   var cell=BuildingTiers.coreCell(t.l,t.e,t.kept());var at=BuildingPlacement.at(t.e,t.kept(),cell.getX(),cell.getY(),cell.getZ());var core=t.l.getBlockState(at);t.l.setBlock(at,Blocks.AIR.defaultBlockState(),2);ScienceWorks.advance(t.l,t.e,1200);h.assertTrue(Population.slots(t.s,t.kept())==6&&scientists(t)==6&&ScienceWorks.places(t.l,t.e)==1&&ScienceWorks.seated(t.l,t.e)==1,"Kept posts preserve their assignments while the existing working-core gate independently limits science");t.l.setBlock(at,core,2);ScienceWorks.advance(t.l,t.e,1220);h.assertTrue(ScienceWorks.places(t.l,t.e)==6&&ScienceWorks.seated(t.l,t.e)==6,"Restoring the actual core restores existing working seats without changing kept appointments");
  }finally{t.close();}h.succeed();
 }
 @GameTest(template="empty",batch="science_staffing_guards",timeoutTicks=200)
 public static void primaryConstructionTransportFoodAndTeacherPostsStillComeFirst(GameTestHelper h){
  var t=town(h);try{paidLabTwo(h,t);for(var r:List.copyOf(t.s.residents()))if(r.profession()==Profession.BUILDER||r.profession()==Profession.PORTER)t.s.unassign(r.id());var school=new Settlement.Building(UUID.randomUUID(),"school",50,0,0);var farm=new Settlement.Building(UUID.randomUUID(),"farm",0,0,24);var restaurant=new Settlement.Building(UUID.randomUUID(),"restaurant",30,0,24);for(var b:List.of(school,farm,restaurant))t.s.addBuilding(b);var child=new Resident(UUID.randomUUID(),Resident.Life.CHILD,false,null,null,-1);t.s.admit(child,t.s.homes().iterator().next().id());var candidates=new ArrayList<Resident>();for(int i=0;i<5;i++)candidates.add(resident(t,true));Population.assign(t.e,2);
   h.assertTrue(t.s.residents().stream().filter(r->r.profession()==Profession.BUILDER).count()==2&&t.s.residents().stream().filter(r->r.profession()==Profession.PORTER).count()==1,"First builder and stock porter remain first; the allowed extra builder remains before additional scientific posts");h.assertTrue(candidates.get(0).profession()==Profession.TEACHER&&candidates.get(1).profession()==Profession.FARMER&&candidates.get(2).profession()==Profession.BAKER&&candidates.get(3).profession()==Profession.BUILDER&&candidates.get(4).profession()==Profession.SCIENTIST,"Teacher for a child, farm, food processing and existing extra-builder priority precede the second scientist");h.assertTrue(scientists(t)==2,"Only the actual remaining lab-II vacancy is filled");
  }finally{t.close();}h.succeed();
 }
 @GameTest(template="empty",batch="science_staffing_guards",timeoutTicks=200)
 public static void onlyHealthyLivingEducatedIdleAdultsTakeScientificVacancies(GameTestHelper h){
  var t=town(h);try{paidLabTwo(h,t);var uneducated=resident(t,false);var ill=resident(t,true);ill.fallIll();var dead=resident(t,true);dead.die();var good=resident(t,true);var employed=resident(t,true);t.s.assign(employed.id(),Profession.BUILDER,t.hall.id());var old=t.s.residents().stream().filter(r->r.profession()==Profession.SCIENTIST).findFirst().orElseThrow();Population.assign(t.l,t.e,2);h.assertTrue(scientists(t)==2&&good.profession()==Profession.SCIENTIST&&uneducated.profession()==null&&ill.profession()==null&&dead.profession()==null&&employed.profession()==Profession.BUILDER&&old.profession()==Profession.SCIENTIST,"Qualifications, life, health, existing assignments and paid original scientist are retained");ill.cure();Population.assign(t.l,t.e,2);h.assertTrue(ill.profession()==null&&scientists(t)==2,"A newly healthy adult cannot overfill the existing two seats");
  }finally{t.close();}h.succeed();
 }
 @GameTest(template="empty",batch="science_staffing_service",timeoutTicks=200)
 public static void twoAutonomouslyAssignedScientistsEachPayTheFullUnchangedWorkPeriod(GameTestHelper h){
  var t=town(h);try{long now=paidLabTwo(h,t);var candidate=resident(t,true);Population.assign(t.l,t.e,1);h.assertTrue(candidate.profession()==Profession.SCIENTIST&&ScienceWorks.advance(t.l,t.e,now)==0&&ScienceWorks.seated(t.l,t.e)==2,"Actual staffing admits the second scientific seat without free output");h.assertTrue(W==36000&&ScienceWorks.advance(t.l,t.e,now+W-1)==0,"Both works still need the full configured 36000-tick village-clock period");h.assertTrue(ScienceWorks.advance(t.l,t.e,now+W)==2&&LogisticsRoutes.chest(t.l,t.e,t.kept()).countItem(VillageAstra.RESEARCH_VOLUME.get())==2,"Two full independent seat periods produce exactly two journal-backed works");h.assertTrue(ScienceWorks.advance(t.l,t.e,now+W)==0&&LogisticsRoutes.chest(t.l,t.e,t.kept()).countItem(VillageAstra.RESEARCH_VOLUME.get())==2,"The same service clock moment cannot duplicate either output");com.mojang.logging.LogUtils.getLogger().info("ZIMBOVILLAGERS_AUTONOMOUS_SCIENCE serviceFixture=true scientists=2 fullWorkTicks={} books=2 noDuplicate=true",W);
  }finally{t.close();}h.succeed();
 }
 @GameTest(template="empty",batch="science_staffing_service",timeoutTicks=200)
 public static void openingAnotherSeatPreservesThePaidOriginalScientistAndHalfFinishedWork(GameTestHelper h){
  var t=town(h);try{long now=paidLabTwo(h,t);var original=NbtRecord.read(ScienceWorks.path(t.l,t.lab.id())).getList("seats",Tag.TAG_COMPOUND).getCompound(0);var id=original.getUUID("worker");ScienceWorks.advance(t.l,t.e,now+W/2);var candidate=resident(t,true);Population.assign(t.l,t.e,1);ScienceWorks.advance(t.l,t.e,now+W/2);var kept=NbtRecord.read(ScienceWorks.path(t.l,t.lab.id())).getList("seats",Tag.TAG_COMPOUND).getCompound(0);h.assertTrue(kept.getUUID("worker").equals(id)&&kept.getLong("since")==original.getLong("since")&&kept.getInt("n")==original.getInt("n"),"Additional staffing preserves original appointment, progress clock and output sequence");h.assertTrue(ScienceWorks.advance(t.l,t.e,now+W)==1&&ScienceWorks.advance(t.l,t.e,now+W+W/2)==1&&candidate.profession()==Profession.SCIENTIST,"Old half-finished place finishes first; new place pays its own full period");
  }finally{t.close();}h.succeed();
 }
 @GameTest(template="empty",batch="science_staffing_custody_diagnostic",timeoutTicks=200)
 public static void pendingCustodyScientificTimerPolicyIsObservedWithoutChangingIt(GameTestHelper h){
  var t=town(h);long now=paidLabTwo(h,t);var r=resident(t,true);t.s.assign(r.id(),Profession.PORTER,t.hall.id());var npc=VillageAstra.RESIDENT.get().create(t.l);npc.bind(t.s.id(),r);npc.setNoAi(true);var at=LogisticsRoutes.position(t.e,t.hall);npc.moveTo(at.getX()+1.5,at.getY(),at.getZ()+.5);SettlementData.get(t.l.getServer()).remove(t.s.id());
  h.startSequence().thenWaitUntil(()->h.assertTrue(t.l.isPositionEntityTicking(npc.blockPosition()),"Actual diagnostic chunk is entity ticking")).thenExecute(()->{h.assertTrue(t.l.getEntity(r.id())==null,"No competing body before canonical admission");SettlementData.get(t.l.getServer()).add(t.e);h.assertTrue(t.l.addFreshEntity(npc)&&t.l.getEntity(r.id())==npc,"Actual canonical diagnostic body is added");}).thenWaitUntil(()->h.assertTrue(npc.tickCount>0,"Diagnostic body actually ticks")).thenExecute(()->{try{var stock=LogisticsRoutes.chest(t.l,t.e,t.hall);stock.setItem(0,new ItemStack(VillageAstra.RESEARCH_VOLUME.get(),2));var route=new LogisticsRoutes.Route(t.hall,t.kept(),new ItemStack(VillageAstra.RESEARCH_VOLUME.get(),2));PorterWork.step(npc,route,false);PorterWork.step(npc);h.assertTrue(PorterWork.cargo(t.l,PorterWork.inspect(t.l,r.id())).getCount()==2&&stock.countItem(VillageAstra.RESEARCH_VOLUME.get())==0,"Real finite two-work parcel is physically paid before unassignment");t.s.unassign(r.id());h.assertTrue(CargoCustody.beginReturn(npc)&&CargoCustody.pending(t.l.getServer(),r.id()),"Actual durable return custody remains incomplete");Population.assign(t.e,1);h.assertTrue(r.profession()==Profession.SCIENTIST&&CargoCustody.pending(t.l.getServer(),r.id())&&!CargoCustody.mayStartWork(npc),"Existing generic staffing admits the pending carrier, while actual work admission still refuses custody");ScienceWorks.advance(t.l,t.e,now);int written=ScienceWorks.advance(t.l,t.e,now+W);h.assertTrue(written==2&&CargoCustody.pending(t.l.getServer(),r.id()),"Existing science service counts assigned scientists independently of pending custody; no new policy is invented");com.mojang.logging.LogUtils.getLogger().info("ZIMBOVILLAGERS_SCIENCE_CUSTODY existingPolicy=true pending=true assignedScientist=true mayStartWork=false fullWorkTicks={} written={} bodyTicks={}",W,written,npc.tickCount);CargoCustody.returnStep(npc,true);CargoCustody.returnStep(npc,true);h.assertTrue(!CargoCustody.pending(t.l.getServer(),r.id())&&stock.countItem(VillageAstra.RESEARCH_VOLUME.get())==2&&LogisticsRoutes.chest(t.l,t.e,t.kept()).countItem(VillageAstra.RESEARCH_VOLUME.get())==2,"Actual return conserves the original two works separately from the two full-period new scientific outputs");}finally{t.close();}}).thenSucceed();
 }
}
