package org.villageastra.gametest;
import java.util.*;
import com.mojang.authlib.GameProfile;
import net.minecraft.core.BlockPos;
import net.minecraft.gametest.framework.*;
import net.minecraft.nbt.*;
import net.minecraft.world.item.ItemStack;
import net.minecraftforge.gametest.*;
import net.minecraftforge.common.util.FakePlayerFactory;
import org.villageastra.VillageAstra;
import org.villageastra.domain.*;
import org.villageastra.persistence.*;
import org.villageastra.server.*;
import org.villageastra.world.*;
@GameTestHolder(VillageAstra.ID) @PrefixGameTestTemplate(false)
public final class BookResearchGameTests {
 private record Bench(GameTestHelper h,SettlementData.Entry e,Settlement.Building lab,OwnedChestEntity chest,net.minecraft.server.level.ServerPlayer mayor){boolean order(String node){var g=e.settlement().governance();return BookResearch.order(mayor,e.settlement().id(),g.epoch(),g.revision(),node);}CompoundTag state(){return BookResearch.inspect(h.getLevel(),e);}void consume(){BookResearch.consume(h.getLevel(),e,lab);}}
 // AD-130/AD-131: the laboratory stands inside the test's own area (east of the forester, south of the mine), clear of the starter farm's west footprint.
 // AD-136: a level-II node costs 7 works (level I is paid in resources); the bench's village has Science I, Agriculture I and Forestry I
 // and a hall of level II, so research.2, agriculture.2 and forestry.2 are the nodes the books buy.
 /** A research record made anew from the village's civilization (its old knowledge migrated), with these nodes already studied. */
 private static void fresh(Bench b,String... learned){var l=b.h().getLevel();try{java.nio.file.Files.deleteIfExists(BookResearch.path(l,b.e().settlement().id()));}catch(java.io.IOException ex){throw new IllegalStateException(ex);}BookResearch.clearCache();
  var record=BookResearch.inspect(l,b.e());var done=record.getList("legacyDone",Tag.TAG_STRING);for(var id:learned)done.add(StringTag.valueOf(id));record.put("legacyDone",done);BookResearch.store(l,b.e(),record);}
 private static Bench bench(GameTestHelper h){return bench(h,"research.1","agriculture.1","forestry.1");}
 private static Bench bench(GameTestHelper h,String... learned){var l=h.getLevel();var s=StarterVillage.create(l,h.absolutePos(new BlockPos(2,3,2)));var e=SettlementData.get(l.getServer()).entry(s.id());var b=new Settlement.Building(UUID.randomUUID(),"laboratory",28,0,24);s.addBuilding(b);l.setBlock(LogisticsRoutes.position(e,b),VillageAstra.OWNED_CHEST.get().defaultBlockState(),3);var p=FakePlayerFactory.get(l,new GameProfile(UUID.randomUUID(),"ResearchMayor"));p.setPos(e.center().getX(),e.center().getY()+1,e.center().getZ());s.appointPlayerMayor(p.getUUID());
  var record=BookResearch.inspect(l,e);var done=record.getList("legacyDone",Tag.TAG_STRING);for(var id:learned)done.add(StringTag.valueOf(id));record.put("legacyDone",done);BookResearch.store(l,e,record);
  if(s.civilization().level()<2)s.civilization().completedHallUpgrade(2);
  return new Bench(h,e,b,LogisticsRoutes.chest(l,e,b),p);}
 @GameTest(template="empty",timeoutTicks=200) public static void sevenPhysicalBooksUnlockOnceAndPartialTargetsSurviveSwitches(GameTestHelper h){var b=bench(h);b.chest.setItem(0,new ItemStack(VillageAstra.RESEARCH_VOLUME.get(),9));h.assertTrue(b.order("research.2"),"Mayor selects available node");b.consume();b.consume();h.assertTrue(b.state().getCompound("paid").getInt("research.2")==2&&b.chest.countItem(VillageAstra.RESEARCH_VOLUME.get())==7,"Two physical works invested");h.assertTrue(b.order("agriculture.2"),"Target can switch");b.consume();h.assertTrue(b.order("research.2"),"Original target resumes");for(int i=0;i<5;i++)b.consume();h.assertTrue(BookResearch.completed(b.e,b.state()).contains("research.2")&&b.state().getCompound("paid").getInt("agriculture.2")==1&&b.chest.countItem(VillageAstra.RESEARCH_VOLUME.get())==1,"Independent payments survive and exactly seven works buy a level-II node");b.consume();h.assertTrue(b.chest.countItem(VillageAstra.RESEARCH_VOLUME.get())==1&&!b.order("research.2"),"Completed node never charges twice");
  // AD-136 (CF3): a level-I node is never a laboratory target nor queued; it is paid in resources.
  h.assertTrue(!b.order("mining.1")&&!BookResearch.order(b.mayor,b.e.settlement().id(),b.e.settlement().governance().epoch(),b.e.settlement().governance().revision(),"mining.1",1),"A level-I node is refused as a target and in the queue");
  h.succeed();}
 @GameTest(template="empty",timeoutTicks=200) public static void receiptAheadOfKnowledgeRecoversOnce(GameTestHelper h){var b=bench(h);b.chest.setItem(0,new ItemStack(VillageAstra.RESEARCH_VOLUME.get(),2));b.order("research.2");var before=b.state();var op=Settlement.childId(b.e.settlement().id(),"book-research/research.2/0");before.putString("pending","research.2");before.putUUID("operation",op);NbtRecord.write(BookResearch.path(h.getLevel(),b.e.settlement().id()),before);BookResearch.clearCache();WorldJournal.takeAmount(h.getLevel(),op,b.chest.getBlockPos(),0,b.chest.getItem(0).copy(),1);BookResearch.recover(h.getLevel(),b.e);BookResearch.recover(h.getLevel(),b.e);h.assertTrue(b.state().getCompound("paid").getInt("research.2")==1&&b.chest.countItem(VillageAstra.RESEARCH_VOLUME.get())==1,"Debited work credited once after restart boundary");h.assertTrue(b.order("agriculture.2")&&b.state().getCompound("paid").getInt("research.2")==1,"Switch preserves recovered investment");h.succeed();}
 @GameTest(template="empty",timeoutTicks=200) public static void authorityLevelsDependenciesAndLegacyKnowledgeStayEnforced(GameTestHelper h){var b=bench(h);var s=b.e.settlement();var g=s.governance();long epoch=g.epoch();s.restoreCivilization(Civilization.restore(1,List.of("cartography"),"ironworking",80));fresh(b,"research.1");h.assertTrue(!b.order("research.2")&&!b.order("unknown.1"),"Tier and catalog checked");s.civilization().completedHallUpgrade(2);h.assertTrue(!b.order("roads.2"),"Prior research required despite hall level");s.restoreCivilization(Civilization.restore(2,List.of("cartography"),"ironworking",80));h.assertTrue(BookResearch.completed(b.e,b.state()).contains("cartography.1")&&s.civilization().progress()==80,"Existing knowledge and paid old topic survive");h.assertTrue(b.order("research.2"),"Current mayor can select");h.assertTrue(!BookResearch.order(b.mayor,s.id(),epoch,0,"agriculture.2"),"Stale revision rejected");s.appointNpcMayor();h.assertTrue(!BookResearch.order(b.mayor,s.id(),epoch,g.revision(),"agriculture.2")&&b.state().getString("selected").equals("research.2"),"Former mayor loses authority without losing research");h.succeed();}
 @GameTest(template="empty",timeoutTicks=200) public static void catalogTechnologyUnlocksQueueAndLegacyCannotBuyNewNodesForPaper(GameTestHelper h){var b=bench(h,"agriculture.1","forestry.1");var s=b.e.settlement();var g=s.governance();h.assertTrue(!BookResearch.order(b.mayor,s.id(),g.epoch(),g.revision(),"agriculture.2",1),"Queue needs Science I");
  // AD-136: Science I is paid in resources from the hall's chest (32 planks, 16 torches, a crafting table), through the mayor's order.
  var hall=LogisticsRoutes.chest(h.getLevel(),b.e,Workshops.hall(b.e));hall.setItem(20,new ItemStack(net.minecraft.world.item.Items.OAK_PLANKS,32));hall.setItem(21,new ItemStack(net.minecraft.world.item.Items.TORCH,16));hall.setItem(22,new ItemStack(net.minecraft.world.item.Items.CRAFTING_TABLE));
  h.assertTrue(BookResearch.order(b.mayor,s.id(),g.epoch(),g.revision(),"research.1",3)&&BookResearch.completed(b.e,b.state()).contains("research.1"),"Science I paid in resources: "+b.state());
  b.chest.setItem(0,new ItemStack(VillageAstra.RESEARCH_VOLUME.get(),14));b.order("research.2");for(int i=0;i<7;i++)b.consume();b.order("agriculture.2");h.assertTrue(BookResearch.order(b.mayor,s.id(),g.epoch(),g.revision(),"forestry.2",1),"Learned catalog enables queue");for(int i=0;i<7;i++)b.consume();h.assertTrue(b.state().getString("selected").equals("forestry.2")&&b.state().getList("queue",8).isEmpty(),"Completing a paid node advances the queue");s.restoreCivilization(Civilization.restore(1,List.of("cartography"),"ironworking",0));h.assertTrue(!BookResearch.completed(b.e,b.state()).contains("cartography.1")&&!BookResearch.legacyAllowed(h.getLevel(),b.e,"ironworking"),"Legacy research created after migration cannot bypass work prices");h.succeed();}
}
