package org.villageastra.gametest;
import java.util.*;
import com.mojang.authlib.GameProfile;
import net.minecraft.core.BlockPos;
import net.minecraft.gametest.framework.*;
import net.minecraft.nbt.*;
import net.minecraft.world.item.*;
import net.minecraft.world.level.block.*;
import net.minecraftforge.gametest.*;
import net.minecraftforge.common.util.FakePlayerFactory;
import org.villageastra.VillageAstra;
import org.villageastra.domain.*;
import org.villageastra.persistence.*;
import org.villageastra.server.*;
import org.villageastra.world.*;
@GameTestHolder(VillageAstra.ID) @PrefixGameTestTemplate(false)
public final class CropPolicyGameTests {
 @GameTest(template="empty",timeoutTicks=200) public static void eachVanillaFoodCropUsesItsOwnMaturity(GameTestHelper h){var l=h.getLevel();var p=h.absolutePos(new BlockPos(3,3,3));l.setBlock(p.below(),Blocks.FARMLAND.defaultBlockState(),3);for(var kind:FarmCrops.values())if(kind.block instanceof CropBlock crop){l.setBlock(p,crop.defaultBlockState(),3);h.assertTrue(FarmCrops.harvest(l,p)==null,"Immature "+kind+" must remain");l.setBlock(p,crop.getStateForAge(crop.getMaxAge()),3);h.assertTrue(p.equals(FarmCrops.harvest(l,p)),"Own max age recognized for "+kind);}h.succeed();}
 @GameTest(template="empty",timeoutTicks=200) public static void buildingPolicyPersistsAndRejectsUnauthorizedRequests(GameTestHelper h){var l=h.getLevel();var s=StarterVillage.create(l,h.absolutePos(new BlockPos(2,3,2)));var e=SettlementData.get(l.getServer()).entry(s.id());/* AD-093: this village has already got hold of carrots and potatoes (their quests are done). */CropUnlocks.unlock(l,e,"minecraft:carrot","quest");CropUnlocks.unlock(l,e,"minecraft:potato","quest");var farm=s.buildings().stream().filter(b->b.type().equals("farm")).findFirst().orElseThrow();var p=FakePlayerFactory.get(l,new GameProfile(UUID.randomUUID(),"FarmPolicy"));p.setPos(e.center().getX(),e.center().getY()+1,e.center().getZ());h.assertTrue(!FarmPolicies.order(p,s.id(),farm.id(),0,0,"carrot"),"Visitor cannot change production");s.appointPlayerMayor(p.getUUID());long epoch=s.governance().epoch();h.assertTrue(FarmPolicies.order(p,s.id(),farm.id(),epoch,0,"carrot"),"Mayor chooses culture");h.assertTrue(!FarmPolicies.order(p,s.id(),farm.id(),epoch,0,"potato")&&!FarmPolicies.order(p,s.id(),UUID.randomUUID(),epoch,1,"potato"),"Stale and foreign building orders rejected");var policies=FarmPolicies.get(l.getServer());var restored=FarmPolicies.load(policies.save(new CompoundTag()));h.assertTrue(restored.crop(s.id(),farm.id())==FarmCrops.CARROT&&restored.crop(s.id(),UUID.randomUUID())==FarmCrops.WHEAT,"Policy persists at building and defaults only for missing entries");s.appointNpcMayor();h.assertTrue(policies.crop(s.id(),farm.id())==FarmCrops.CARROT&&!FarmPolicies.order(p,s.id(),farm.id(),epoch,1,"potato"),"Succession retains policy but revokes former actor");h.succeed();}
 @GameTest(template="empty",timeoutTicks=200) public static void caneHarvestKeepsRootAndRequiresWater(GameTestHelper h){var l=h.getLevel();var p=h.absolutePos(new BlockPos(3,3,3));l.setBlock(p.below(),Blocks.DIRT.defaultBlockState(),3);h.assertTrue(!FarmCrops.SUGAR_CANE.canPrepare(l,p),"Dry site is not a cane field");l.setBlock(p.below().east(),Blocks.WATER.defaultBlockState(),3);h.assertTrue(FarmCrops.SUGAR_CANE.canPrepare(l,p),"Natural waterside soil allowed");for(int y=0;y<3;y++)l.setBlock(p.above(y),Blocks.SUGAR_CANE.defaultBlockState(),3);h.assertTrue(FarmCrops.harvest(l,p).equals(p.above(2)),"Only topmost cane is selected");var loot=WorldJournal.harvest(l,UUID.randomUUID(),p.above(2),l.getBlockState(p.above(2)),new ItemStack(Items.STONE_HOE));h.assertTrue(loot!=null&&loot.stream().filter(i->i.is(Items.SUGAR_CANE)).mapToInt(ItemStack::getCount).sum()==1&&l.getBlockState(p).is(Blocks.SUGAR_CANE)&&l.getBlockState(p.above()).is(Blocks.SUGAR_CANE),"Physical harvest returns one cane and leaves lower growth");l.setBlock(p.above(),Blocks.AIR.defaultBlockState(),3);h.assertTrue(FarmCrops.harvest(l,p)==null,"Single root is never harvested");h.succeed();}
 @GameTest(template="empty",timeoutTicks=200) public static void carriedCarrotRemainsCarrotOnWorkerDeath(GameTestHelper h){var l=h.getLevel();var origin=h.absolutePos(new BlockPos(2,3,2));var s=StarterVillage.create(l,origin);var r=s.residents().stream().filter(p->p.profession()==Profession.FARMER).findFirst().orElseThrow();var worker=(ResidentEntity)l.getEntity(r.id());var chest=(OwnedChestEntity)l.getBlockEntity(origin.offset(1,1,4));chest.setItem(20,new ItemStack(Items.CARROT,3));var id=UUID.randomUUID();WorldJournal.take(l,id,chest.getBlockPos(),20,chest.getItem(20).copy());var state=new CompoundTag();state.putInt("schema",1);state.putUUID("worker",worker.getUUID());state.putUUID("operation",id);state.putString("stage","plant");state.putString("crop","carrot");state.putLong("target",origin.offset(2,1,22).asLong());NbtRecord.write(l.getServer().getWorldPath(net.minecraft.world.level.storage.LevelResource.ROOT).resolve("data/astra-work/"+s.workplace(r.id()).id()+".bin"),state);var cargo=JobCargo.snapshot(worker,true).items();h.assertTrue(cargo.stream().map(t->ItemStack.of((CompoundTag)t)).filter(i->i.is(Items.CARROT)).mapToInt(ItemStack::getCount).sum()==1&&cargo.stream().map(t->ItemStack.of((CompoundTag)t)).noneMatch(i->i.is(Items.WHEAT_SEEDS))&&chest.countItem(Items.CARROT)==2,"The exact withdrawn seed is preserved without conversion or a second debit");h.succeed();}
}
