package org.villageastra.gametest;
import java.util.*;
import net.minecraft.core.BlockPos;
import net.minecraft.core.registries.*;
import net.minecraft.gametest.framework.*;
import net.minecraft.nbt.*;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.tags.TagKey;
import net.minecraft.world.item.*;
import net.minecraft.world.level.block.Blocks;
import net.minecraftforge.gametest.*;
import org.villageastra.VillageAstra;
import org.villageastra.domain.*;
import org.villageastra.server.*;
import org.villageastra.world.*;
import org.villageastra.persistence.*;
/** AD474: a finite paid parcel must not pin the stock porter after scientific outputs fill its destination. */
@GameTestHolder(VillageAstra.ID) @PrefixGameTestTemplate(false)
public final class LabParcelOverflowGameTests {
 private static int serial;
 private static final long W=ScienceBalance.WORK_TICKS;
 private record Town(net.minecraft.server.level.ServerLevel l,SettlementData.Entry e,Settlement s,Settlement.Building hall,Settlement.Building lab,List<net.minecraft.world.level.ChunkPos> held){
  Settlement.Building kept(){return s.buildings().stream().filter(b->b.id().equals(lab.id())).findFirst().orElseThrow();}
  void close(){for(var r:s.residents())if(l.getEntity(r.id()) instanceof ResidentEntity body)body.discard();SettlementData.get(l.getServer()).remove(s.id());BuildingLevels.forgetBest(s.id());BookResearch.clearCache();PhysicalFixtureChunks.release(l,held);}
 }
 private static Resident resident(Town t,boolean educated){var r=new Resident(UUID.randomUUID(),Resident.Life.ADULT,educated,null,null,-1);t.s.admit(r,t.s.homes().iterator().next().id());return r;}
 private static Town town(GameTestHelper h){
  var l=h.getLevel();var at=h.absolutePos(BlockPos.ZERO);var center=new BlockPos(at.getX()+4718592+(serial++)*128,110,at.getZ());var held=PhysicalFixtureChunks.force(l,center,-3,80,-3,18);for(var c:held)l.getChunk(c.x,c.z);for(var p:BlockPos.betweenClosed(center.offset(-3,-1,-3),center.offset(80,18,18)))l.setBlock(p,p.getY()<center.getY()?Blocks.STONE.defaultBlockState():Blocks.AIR.defaultBlockState(),2);
  var s=new Settlement(UUID.randomUUID());var hall=new Settlement.Building(UUID.randomUUID(),"town_hall",0,0,0);var lab=new Settlement.Building(UUID.randomUUID(),"laboratory",30,0,0);s.addBuilding(hall);s.addBuilding(lab);s.addHome(new Settlement.Home(UUID.randomUUID(),1,32,true));var e=new SettlementData.Entry(s,l.dimension().location().toString(),center);SettlementData.get(l.getServer()).add(e);ResearchV2Town.lay(l,e,hall,"town_hall");ResearchV2Town.lay(l,e,lab,"laboratory");var t=new Town(l,e,s,hall,lab,held);var builder=resident(t,false);s.assign(builder.id(),Profession.BUILDER,hall.id());var porter=resident(t,false);s.assign(porter.id(),Profession.PORTER,hall.id());var scientist=resident(t,true);s.assign(scientist.id(),Profession.SCIENTIST,lab.id());BookResearch.clearCache();return t;
 }
 private static long paidLabTwo(GameTestHelper h,Town t){
  var node=ResearchCatalog.get("research.1");var stock=LogisticsRoutes.chest(t.l,t.e,t.hall);stock.clearContent();int slot=0;for(var c:node.resources()){var item=c.tag()==null?BuiltInRegistries.ITEM.get(new ResourceLocation(c.item())):BuiltInRegistries.ITEM.getTagOrEmpty(TagKey.create(Registries.ITEM,new ResourceLocation(c.tag()))).iterator().next().value();stock.setItem(slot++,new ItemStack(item,c.count()));}h.assertTrue(BookResearch.payResources(t.l,t.e,node.id())&&stock.isEmpty(),"Science I is really paid in the full published resources");
  h.assertTrue(BookResearch.autoSelect(t.l,t.e).equals("town_hall.2"),"Actual next-hall exception opens the bootstrap scientific target");long now=0;h.assertTrue(ScienceWorks.advance(t.l,t.e,now)==0,"Initial science grants no books");now=spend(h,t,"town_hall.2",now);t.s.civilization().completedHallUpgrade(2);ResearchV2Town.lay(t.l,t.e,t.hall,BuildingTiers.layoutId("town_hall",2));BuildingLevels.forgetBest(t.s.id());h.assertTrue(BookResearch.autoSelect(t.l,t.e).equals("research.2"),"Actual NPC selects Science II after the independent initial hall-II fixture stands");now=spend(h,t,"research.2",now);t.s.raiseBuildingLevel(t.lab.id(),2);ResearchV2Town.lay(t.l,t.e,t.kept(),BuildingTiers.layoutId("laboratory",2));BuildingLevels.forgetBest(t.s.id());
  h.assertTrue(LogisticsRoutes.chest(t.l,t.e,t.kept())!=null&&BuildingTiers.level(t.l,t.e,t.kept())==2&&ScienceWorks.places(t.l,t.e)==2&&BookResearch.inspect(t.l,t.e).getList("legacyDone",Tag.TAG_STRING).isEmpty()&&ResearchGate.has(t.l,t.e,"research.2"),"Physical lab-II core and equipment stand with seven actually paid works and no legacy knowledge grants");return now;
 }
 private static long spend(GameTestHelper h,Town t,String id,long now){int works=ResearchCatalog.get(id).works();h.assertTrue(ScienceWorks.advance(t.l,t.e,now+works*W)==works,"Every scientific work takes its full unchanged WORK_TICKS period");for(int i=0;i<works;i++)h.assertTrue(BookResearch.consume(t.l,t.e,t.kept()),"Actual research consumes produced work "+i);h.assertTrue(ResearchGate.has(t.l,t.e,id)&&LogisticsRoutes.chest(t.l,t.e,t.kept()).countItem(VillageAstra.RESEARCH_VOLUME.get())==0,"All produced works are spent exactly once");return now+works*W;}
 @GameTest(template="empty",batch="lab_parcel_overflow",timeoutTicks=1600)
 public static void paidWorksReturnWhenTwoScientificSeatsFillTheDestination(GameTestHelper h){journey(h,0);}
 @GameTest(template="empty",batch="lab_parcel_overflow",timeoutTicks=1600)
 public static void aFreeLaboratoryStillReceivesItsOriginalPaidWorks(GameTestHelper h){journey(h,1);}
 @GameTest(template="empty",batch="lab_parcel_overflow",timeoutTicks=1600)
 public static void anExistingUncommittedPutKeepsItsOriginalLaboratoryDestination(GameTestHelper h){journey(h,2);}
 private static BlockPos initialStand(GameTestHelper h,Town t,ResidentEntity npc,BlockPos chest){
  for(var at:BlockPos.betweenClosed(chest.offset(-2,0,-2),chest.offset(3,1,2))){var point=net.minecraft.world.phys.Vec3.atBottomCenterOf(at);var box=npc.getBoundingBox().move(point.subtract(npc.position()));if(point.distanceToSqr(new net.minecraft.world.phys.Vec3(chest.getX()+1.5,chest.getY(),chest.getZ()+.5))<=6.25&&t.l.getBlockState(at.below()).isFaceSturdy(t.l,at.below(),net.minecraft.core.Direction.UP)&&t.l.noCollision(npc,box))return at.immutable();}
  h.assertTrue(false,"Physical fixture has a supported free initial stand within normal take reach");return chest;
 }
 @GameTest(template="empty",batch="lab_parcel_overflow",timeoutTicks=1600)
 public static void paidWarehouseWorksPhysicallyReturnToTheHallAndReleaseTheirPorter(GameTestHelper h){journey(h,3);}
 private static void clearCustodyReader(Town t)throws Exception{var f=CargoCustody.class.getDeclaredField("CACHE");f.setAccessible(true);((Map<?,?>)f.get(null)).remove(t.l.getServer());}
 private static void journey(GameTestHelper h,int mode){
  var t=town(h);long now=paidLabTwo(h,t);var second=resident(t,true);Population.assign(t.l,t.e,1);h.assertTrue(second.profession()==Profession.SCIENTIST&&ScienceWorks.advance(t.l,t.e,now)==0&&ScienceWorks.seated(t.l,t.e)==2,"The actual paid physical laboratory has two scientific seats");
  Settlement.Building sourcePost=t.hall;if(mode==3){sourcePost=new Settlement.Building(UUID.randomUUID(),"warehouse",50,0,0);t.s.addBuilding(sourcePost);ResearchV2Town.lay(t.l,t.e,sourcePost,"warehouse");}final var source=sourcePost;var sourcePos=LogisticsRoutes.position(t.e,source);
  var r=t.s.residents().stream().filter(x->x.profession()==Profession.PORTER).findFirst().orElseThrow();var npc=VillageAstra.RESIDENT.get().create(t.l);npc.bind(t.s.id(),r);npc.setNoAi(false);var hallPos=LogisticsRoutes.position(t.e,t.hall);var labPos=LogisticsRoutes.position(t.e,t.kept());var start=initialStand(h,t,npc,sourcePos);npc.moveTo(start.getX()+.5,start.getY(),start.getZ()+.5);SettlementData.get(t.l.getServer()).remove(t.s.id());float health=npc.getHealth();boolean[] returning={false},closed={false};CompoundTag[] parcel={null};UUID[] put={null};
  npc.goalSelector.removeAllGoals(g->!(g instanceof ResidentDoorGoal));npc.targetSelector.removeAllGoals(g->true);npc.goalSelector.addGoal(4,new net.minecraft.world.entity.ai.goal.Goal(){
   {setFlags(EnumSet.of(Flag.MOVE,Flag.LOOK));}public boolean canUse(){return returning[0]&&CargoCustody.pending(t.l.getServer(),r.id());}public boolean requiresUpdateEveryTick(){return true;}public void tick(){if(npc.tickCount%20==0)CargoCustody.returnStep(npc,true);}
  });
  h.startSequence().thenWaitUntil(()->h.assertTrue(t.l.isPositionEntityTicking(npc.blockPosition()),"Canonical porter chunk is entity ticking")).thenExecute(()->{h.assertTrue(t.l.getEntity(r.id())==null,"No competing body before synchronous admission");SettlementData.get(t.l.getServer()).add(t.e);h.assertTrue(t.l.addFreshEntity(npc)&&t.l.getEntity(r.id())==npc,"Actual canonical porter is added");}).thenWaitUntil(()->h.assertTrue(npc.tickCount>2&&npc.onGround(),"Actual porter settles on its supported initial stand")).thenExecute(()->{
   var stock=LogisticsRoutes.chest(t.l,t.e,source);stock.clearContent();stock.setItem(0,new ItemStack(VillageAstra.RESEARCH_VOLUME.get(),7));PorterWork.step(npc);var planned=PorterWork.inspect(t.l,r.id());h.assertTrue(PorterWork.active(planned)&&planned.getUUID("destination").equals(t.lab.id())&&planned.getUUID("source").equals(source.id()),"Actual choose plans the finite seven-work laboratory demand");PorterWork.step(npc);parcel[0]=PorterWork.inspect(t.l,r.id());put[0]=Settlement.childId(parcel[0].getUUID("id"),"put");h.assertTrue(PorterWork.cargo(t.l,parcel[0]).getCount()==7&&stock.countItem(VillageAstra.RESEARCH_VOLUME.get())==0&&!WorldJournal.exists(t.l,put[0]),"Actual take physically pays seven works without a phantom put");
   npc.setNoAi(false);var path=ResourceReturnRoute.plan(npc,labPos.east());h.assertTrue(path!=null&&path.canReach()&&npc.getNavigation().moveTo(path,.8),"Native walking route reaches the real laboratory chest: start="+npc.position()+" feet="+t.l.getBlockState(npc.blockPosition())+" target="+t.l.getBlockState(labPos.east())+" path="+(path==null?"null":path.canReach()+"/"+path.getEndNode()));
  }).thenWaitUntil(()->h.assertTrue(npc.distanceToSqr(labPos.getX()+1.5,labPos.getY(),labPos.getZ()+.5)<=6.25,"Actual porter physically reaches the laboratory after payment")).thenExecute(()->{
   var labStock=LogisticsRoutes.chest(t.l,t.e,t.kept());var stock=LogisticsRoutes.chest(t.l,t.e,t.hall);h.assertTrue(npc.getHealth()==health&&t.l.getEntity(r.id())==npc,"Physical outgoing walk preserves health and canonical identity");
   if(mode==1){PorterWork.step(npc);h.assertTrue(!PorterWork.active(PorterWork.inspect(t.l,r.id()))&&!CargoCustody.pending(t.l.getServer(),r.id())&&labStock.countItem(VillageAstra.RESEARCH_VOLUME.get())==7&&stock.countItem(VillageAstra.RESEARCH_VOLUME.get())==0&&WorldJournal.inspectCommitted(t.l,put[0])!=null,"Ordinary destination receives the original paid seven works exactly once");NbtRecord.write(PorterWork.path(t.l,r.id()),parcel[0]);PorterWork.step(npc);h.assertTrue(labStock.countItem(VillageAstra.RESEARCH_VOLUME.get())==7&&!PorterWork.active(PorterWork.inspect(t.l,r.id())),"An old paid checkpoint cannot duplicate normal delivery");closed[0]=true;t.close();return;}
   if(mode==2){WorldJournal.batch(t.l,()->{h.assertTrue(WorldJournal.deposit(t.l,put[0],labPos,new ItemStack(VillageAstra.RESEARCH_VOLUME.get(),7))&&WorldJournal.exists(t.l,put[0])&&WorldJournal.inspectCommitted(t.l,put[0])==null,"A real journal batch has applied the original seven-work put but not committed its intent");for(int i=1;i<labStock.getContainerSize();i++)labStock.setItem(i,new ItemStack(Items.COBBLESTONE,64));h.assertTrue(ScienceWorks.advance(t.l,t.e,now+32*W)==57&&labStock.countItem(VillageAstra.RESEARCH_VOLUME.get())==64,"The real put occupies seven places in the stack; full-period science occupies the remaining57");PorterWork.step(npc);h.assertTrue(!CargoCustody.pending(t.l.getServer(),r.id())&&!PorterWork.active(PorterWork.inspect(t.l,r.id())),"An existing uncommitted original put is recovered without redirection into return custody");return null;});h.assertTrue(WorldJournal.inspectCommitted(t.l,put[0])!=null&&labStock.countItem(VillageAstra.RESEARCH_VOLUME.get())==64&&stock.countItem(VillageAstra.RESEARCH_VOLUME.get())==0,"The original deposit commits at the original address without losing or duplicating works");closed[0]=true;t.close();return;}
   for(int i=0;i<labStock.getContainerSize()-1;i++)labStock.setItem(i,new ItemStack(Items.COBBLESTONE,64));h.assertTrue(ScienceWorks.advance(t.l,t.e,now+32*W)==64&&labStock.countItem(VillageAstra.RESEARCH_VOLUME.get())==64,"Two scientific seats physically write64 outputs after32 full WORK_TICKS periods each");h.assertTrue(!BookResearch.selected(t.l,t.e)&&!BookResearch.consume(t.l,t.e,t.kept()),"The actual empty research target drains no scientific output");
   var mine=new Settlement.Building(UUID.randomUUID(),"mine",mode==3?15:50,0,0);t.s.addBuilding(mine);var minePos=LogisticsRoutes.position(t.e,mine);t.l.setBlock(minePos,VillageAstra.OWNED_CHEST.get().defaultBlockState(),2);LogisticsRoutes.chest(t.l,t.e,mine).setItem(0,new ItemStack(Items.COBBLESTONE,16));var next=LogisticsRoutes.choose(t.l,t.e,t.hall,npc.blockPosition());h.assertTrue(next!=null&&next.source().id().equals(mine.id())&&next.destination().id().equals(t.hall.id())&&next.item().is(Items.COBBLESTONE),"Actual stock-supply planning has another admissible finite route");
   PorterWork.step(npc);h.assertTrue(CargoCustody.pending(t.l.getServer(),r.id())&&!WorldJournal.exists(t.l,put[0])&&npc.distanceToSqr(hallPos.getX()+1.5,hallPos.getY(),hallPos.getZ()+.5)>6.25&&stock.countItem(VillageAstra.RESEARCH_VOLUME.get())==0,"The full paid parcel enters durable return at its actual distant location without remote delivery");var custody=CargoCustody.inspect(t.l.getServer(),r.id());h.assertTrue(custody.getList("items",Tag.TAG_COMPOUND).getCompound(0).getByte("Count")==7,"Durable custody contains exactly the seven paid works");try{clearCustodyReader(t);}catch(Exception ex){throw new RuntimeException(ex);}h.assertTrue(CargoCustody.inspect(t.l.getServer(),r.id()).equals(custody),"A fresh custody reader reloads the same signed return checkpoint");returning[0]=true;
  }).thenWaitUntil(()->h.assertTrue(closed[0]||returning[0]&&!CargoCustody.pending(t.l.getServer(),r.id()),"Actual return walk and journal-backed unloading complete")).thenExecute(()->{if(closed[0])return;try{
   var stock=LogisticsRoutes.chest(t.l,t.e,t.hall);var labStock=LogisticsRoutes.chest(t.l,t.e,t.kept());h.assertTrue(stock.countItem(VillageAstra.RESEARCH_VOLUME.get())==7&&labStock.countItem(VillageAstra.RESEARCH_VOLUME.get())==64&&!PorterWork.active(PorterWork.inspect(t.l,r.id()))&&!WorldJournal.exists(t.l,put[0])&&LogisticsRoutes.chest(t.l,t.e,source).countItem(VillageAstra.RESEARCH_VOLUME.get())==(mode==3?0:7)&&npc.getHealth()==health,"Physical return conserves all71 works, releases the original job and preserves health");var completed=CargoCustody.inspect(t.l.getServer(),r.id());try{clearCustodyReader(t);}catch(Exception ex){throw new RuntimeException(ex);}CargoCustody.returnStep(npc,true);CargoCustody.returnStep(npc,true);h.assertTrue(CargoCustody.inspect(t.l.getServer(),r.id()).equals(completed)&&stock.countItem(VillageAstra.RESEARCH_VOLUME.get())==7&&labStock.countItem(VillageAstra.RESEARCH_VOLUME.get())==64,"Reload and repeated return cannot duplicate either paid or earned works");PorterWork.step(npc);var newJob=PorterWork.inspect(t.l,r.id());h.assertTrue(PorterWork.active(newJob)&&!newJob.getUUID("id").equals(parcel[0].getUUID("id"))&&ItemStack.of(newJob.getCompound("item")).is(Items.COBBLESTONE),"The same actual porter resumes the independent needed stock-supply route");com.mojang.logging.LogUtils.getLogger().info("ZIMBOVILLAGERS_LAB_OVERFLOW fixed=true physical=true reload=true earned64=true returned7=true newSupply=true warehouse={} bodyTicks={}",mode==3,npc.tickCount);
  }finally{closed[0]=true;t.close();}}).thenSucceed();
  h.runAtTickTime(1550,()->{if(closed[0])return;String why="Physical lab parcel journey stalled mode="+mode+" pos="+npc.position()+" bodyTicks="+npc.tickCount+" grounded="+npc.onGround()+" noAi="+npc.isNoAi()+" returning="+returning[0]+" pending="+CargoCustody.pending(t.l.getServer(),r.id());closed[0]=true;t.close();h.assertTrue(false,why);});
 }
}
