package org.villageastra.gametest;
import java.util.*;
import net.minecraft.core.BlockPos;
import net.minecraft.gametest.framework.*;
import net.minecraft.nbt.*;
import net.minecraft.world.item.*;
import net.minecraftforge.gametest.*;
import org.villageastra.VillageAstra;
import org.villageastra.domain.*;
import org.villageastra.persistence.*;
import org.villageastra.server.*;
import org.villageastra.world.*;
@GameTestHolder(VillageAstra.ID) @PrefixGameTestTemplate(false)
public final class LogisticsGameTests {
 private record Fixture(GameTestHelper h,SettlementData.Entry e,ResidentEntity worker,Settlement.Building farm,Settlement.Building lab,OwnedChestEntity source,OwnedChestEntity dest){CompoundTag state(){return PorterWork.inspect(h.getLevel(),worker.getUUID());}void at(Settlement.Building b){var p=LogisticsRoutes.position(e,b);worker.moveTo(p.getX()+1.5,p.getY(),p.getZ()+.5);}void step(){PorterWork.step(worker);}void done(){for(var r:e.settlement().residents())if(h.getLevel().getEntity(r.id()) instanceof ResidentEntity npc)npc.discard();SettlementData.get(h.getLevel().getServer()).remove(e.settlement().id());RestaurantFixture.release(h.getLevel(),e.settlement().id());}}
 // AD-136: the porter brings scientific works to the laboratory while it holds fewer than 7: it holds 1, so 6 of the 7 works lying in
 // the farm chest travel (the old paper-chain demand for sugar cane is gone).
 // AD-131: the laboratory's chest lies south of where the neighbouring test's starter mine (x 32..39, z 12..20) now stands.
 private static Fixture fixture(GameTestHelper h){var l=h.getLevel();var origin=h.absolutePos(new BlockPos(2,3,2));RestaurantFixture.hold(l,StarterVillage.id(l,origin),origin.offset(-20,-8,-8),origin.offset(72,0,56));for(var p:StarterVillage.layout(origin).keySet())l.setBlock(p,net.minecraft.world.level.block.Blocks.AIR.defaultBlockState(),2);var s=StarterVillage.create(l,origin);for(var r:s.residents())((ResidentEntity)l.getEntity(r.id())).setNoAi(true);var e=SettlementData.get(l.getServer()).entry(s.id());var farm=s.buildings().stream().filter(b->b.type().equals("farm")).findFirst().orElseThrow();var lab=new Settlement.Building(UUID.randomUUID(),"laboratory",-16,0,22);s.addBuilding(lab);l.setBlock(LogisticsRoutes.position(e,lab),VillageAstra.OWNED_CHEST.get().defaultBlockState(),3);var source=LogisticsRoutes.chest(l,e,farm);source.clearContent();source.setItem(0,new ItemStack(VillageAstra.RESEARCH_VOLUME.get(),7));source.setItem(1,new ItemStack(Items.WHEAT_SEEDS,8));var dest=LogisticsRoutes.chest(l,e,lab);dest.setItem(0,new ItemStack(VillageAstra.RESEARCH_VOLUME.get(),1));var worker=(ResidentEntity)l.getEntity(s.residents().stream().filter(r->r.profession()==Profession.PORTER).findFirst().orElseThrow().id());return new Fixture(h,e,worker,farm,lab,source,dest);}
 @GameTest(template="empty",batch="logistics_physicalTransportReservesSeedsAndReplaysBothReceipts",timeoutTicks=200) public static void physicalTransportReservesSeedsAndReplaysBothReceipts(GameTestHelper h){var f=fixture(h);f.step();var planned=f.state();f.at(f.farm);f.step();h.assertTrue(f.source.countItem(VillageAstra.RESEARCH_VOLUME.get())==1&&f.dest.countItem(VillageAstra.RESEARCH_VOLUME.get())==1&&PorterWork.cargo(h.getLevel(),f.state()).getCount()==6,"Six works in the real carrier, one remains, no remote delivery");NbtRecord.write(PorterWork.path(h.getLevel(),f.worker.getUUID()),planned);f.at(f.lab);f.step();h.assertTrue(f.source.countItem(VillageAstra.RESEARCH_VOLUME.get())==1&&f.dest.countItem(VillageAstra.RESEARCH_VOLUME.get())==7,"Input journal ahead of state resumes without second debit");NbtRecord.write(PorterWork.path(h.getLevel(),f.worker.getUUID()),planned);f.step();h.assertTrue(f.dest.countItem(VillageAstra.RESEARCH_VOLUME.get())==7&&!PorterWork.active(f.state()),"Output journal ahead of state cannot duplicate delivery");f.done();h.succeed();}
 @GameTest(template="empty",batch="logistics_unpaidFullDestination",timeoutTicks=200) public static void anUnpaidRouteToAFilledChestReturnsToPlanningWithoutTakingGoods(GameTestHelper h){
  var f=fixture(h);f.step();var planned=f.state();h.assertTrue(ItemStack.of(planned.getCompound("item")).is(VillageAstra.RESEARCH_VOLUME.get()),"The intended parcel is planned before its destination fills");
  for(int i=0;i<f.dest.getContainerSize();i++)f.dest.setItem(i,new ItemStack(Items.COBBLESTONE,64));f.at(f.farm);f.step();
  h.assertTrue(f.source.countItem(VillageAstra.RESEARCH_VOLUME.get())==7&&!PorterWork.active(f.state())&&!WorldJournal.exists(h.getLevel(),Settlement.childId(planned.getUUID("id"),"take")),"An unpaid route is cancelled without withdrawal or receipt");f.done();h.succeed();
 }
 @GameTest(template="empty",batch="logistics_fullDestinationAndReassignmentKeepPhysicalCustody",timeoutTicks=200) public static void fullDestinationAndReassignmentKeepPhysicalCustody(GameTestHelper h){var f=fixture(h);f.step();f.at(f.farm);f.step();for(int i=0;i<f.dest.getContainerSize();i++)f.dest.setItem(i,new ItemStack(Items.COBBLESTONE,64));f.at(f.lab);f.step();h.assertTrue(PorterWork.active(f.state())&&PorterWork.cargo(h.getLevel(),f.state()).getCount()==6,"Full chest retains parcel");var s=f.e.settlement();s.assign(f.worker.getUUID(),Profession.BUILDER,s.workplace(f.worker.getUUID()).id());h.assertTrue(CargoCustody.beginReturn(f.worker),"Role change creates custody return");CargoCustody.returnStep(f.worker,true);var hall=s.buildings().stream().filter(b->b.type().equals("town_hall")).findFirst().orElseThrow();var c=LogisticsRoutes.chest(h.getLevel(),f.e,hall);h.assertTrue(c.countItem(VillageAstra.RESEARCH_VOLUME.get())==0,"Return does not teleport");f.at(hall);CargoCustody.returnStep(f.worker,false);h.assertTrue(c.countItem(VillageAstra.RESEARCH_VOLUME.get())==0,"Paused return changes nothing");CargoCustody.returnStep(f.worker,true);CargoCustody.returnStep(f.worker,true);h.assertTrue(c.countItem(VillageAstra.RESEARCH_VOLUME.get())==6&&!PorterWork.active(f.state()),"Actual return closes original parcel");f.done();h.succeed();}
 @GameTest(template="empty",batch="logistics_deathDropsTheParcelExactlyOnce",timeoutTicks=200) public static void deathDropsTheParcelExactlyOnce(GameTestHelper h){var f=fixture(h);f.step();f.at(f.farm);f.step();f.worker.hurt(h.getLevel().damageSources().genericKill(),1000);CargoCustody.tick(h.getLevel().getServer());var state=CargoCustody.inspect(h.getLevel().getServer(),f.worker.getUUID());var pos=BlockPos.of(state.getList("drops",10).getCompound(0).getLong("pos"));var pile=(net.minecraft.world.Container)h.getLevel().getBlockEntity(pos);h.assertTrue(pile.countItem(VillageAstra.RESEARCH_VOLUME.get())==6&&f.source.countItem(VillageAstra.RESEARCH_VOLUME.get())==1&&f.dest.countItem(VillageAstra.RESEARCH_VOLUME.get())==1,"Only paid physical parcel remains at death");pile.clearContent();CargoCustody.onDeath(f.worker);CargoCustody.recover(h.getLevel().getServer());h.assertTrue(pile.isEmpty(),"Looted parcel never refills");f.done();h.succeed();}
 @GameTest(template="empty",batch="logistics_planningReservesFiniteSourcesAndRejectsUnpaidCargo",timeoutTicks=200) public static void planningReservesFiniteSourcesAndRejectsUnpaidCargo(GameTestHelper h){var f=fixture(h);f.step();h.assertTrue(PorterWork.reserved(h.getLevel(),f.e,f.farm.id(),s->s.is(VillageAstra.RESEARCH_VOLUME.get()),false)==6&&PorterWork.reserved(h.getLevel(),f.e,f.lab.id(),s->s.is(VillageAstra.RESEARCH_VOLUME.get()),true)==6,"Source and destination are reserved before withdrawal");var next=LogisticsRoutes.choose(h.getLevel(),f.e);h.assertTrue(next==null||!next.item().is(VillageAstra.RESEARCH_VOLUME.get()),"Another planner cannot promise the same works");var state=f.state();state.putString("stage","deliver");NbtRecord.write(PorterWork.path(h.getLevel(),f.worker.getUUID()),state);f.at(f.lab);boolean rejected=false;try{f.step();}catch(IllegalStateException ex){rejected=true;}h.assertTrue(rejected&&f.dest.countItem(VillageAstra.RESEARCH_VOLUME.get())==1&&f.source.countItem(VillageAstra.RESEARCH_VOLUME.get())==7,"Forged delivery state cannot mint unpaid items");f.done();h.succeed();}
}
