package org.villageastra.gametest;
import java.util.*;
import net.minecraft.core.*;
import net.minecraft.gametest.framework.*;
import net.minecraft.nbt.*;
import net.minecraft.world.item.*;
import net.minecraft.world.level.block.Blocks;
import net.minecraftforge.gametest.*;
import org.villageastra.VillageAstra;
import org.villageastra.domain.*;
import org.villageastra.server.*;
import org.villageastra.world.*;
@GameTestHolder(VillageAstra.ID) @PrefixGameTestTemplate(false)
public final class MineProspectingGameTests {
 private record Town(ResearchV2Town.Town town,ResidentEntity npc,CompoundTag state){}
 private static Town town(GameTestHelper h){
  var old=ResearchV2Town.town(h,"mine");var data=SettlementData.get(old.l.getServer());data.remove(old.s.id());var e=new SettlementData.Entry(old.s,old.e.dimension(),new BlockPos(old.e.center().getX(),64,old.e.center().getZ()));data.add(e);
  var t=new ResearchV2Town.Town(old.l,e,old.s,old.shop);ResearchV2Town.lay(t.l,e,t.shop,"mine");t.l.setBlock(e.center().offset(1,1,4),VillageAstra.OWNED_CHEST.get().defaultBlockState(),2);
  var npc=VillageAstra.RESIDENT.get().create(t.l);var r=new Resident(npc.getUUID(),Resident.Life.ADULT,true,null,null,-1);t.s.admit(r,Settlement.childId(t.s.id(),"home"));t.s.assign(r.id(),Profession.MINER,t.shop.id());npc.bind(t.s.id(),t.s.resident(r.id()));npc.setNoAi(true);
  var state=MineWork.read(t.l,t.shop);int floor=MineWork.floorStep(t.l,e,t.shop,state);state.putInt("floorStep",floor);state.putInt("extentStep",floor);state.putInt("stairAudit",floor+1);state.putInt("step",floor+1);state.putInt("side",MineDrive.DONE);state.put("tool",new ItemStack(Items.STONE_PICKAXE).save(new CompoundTag()));t.s.noteMine(t.shop.id(),floor,3,5,7);MineWork.write(t.l,t.shop,state);
  var project=new CompoundTag();project.putUUID("id",UUID.randomUUID());var cost=new CompoundTag();cost.putInt("minecraft:lantern",3);project.put("cost",cost);HallUpgradeGoal.store(t.l,t.s.id(),project);
  var hall=LogisticsRoutes.chest(t.l,e,Workshops.hall(e));hall.clearContent();hall.setItem(0,new ItemStack(Items.COAL,8));hall.setItem(1,new ItemStack(Items.STICK,8));
  return new Town(t,npc,state);
 }
 @GameTest(template="empty",batch="mine_prospect",timeoutTicks=200)
 public static void missingOreStartsShallowerBranchAndActuallyMinesItAfterReload(GameTestHelper h){
  var f=town(h);var t=f.town;try{
   h.assertTrue(MineProspecting.begin(t.l,t.e,t.shop,f.state),"An exhausted mine with an unfunded iron order starts prospecting");
   h.assertTrue(f.state.getInt("floorStep")==18&&f.state.getInt("extentStep")==25,"A new branch uses existing shallower stairs and preserves the deepest claim");
   MineWork.write(t.l,t.shop,f.state);var saved=MineWork.read(t.l,t.shop);var next=MineWork.next(t.l,t.e,t.shop,saved);h.assertTrue(next.stage()==MineDrive.Stage.EAST&&saved.getInt("floorStep")==18,"Reload retains its survey floor");
   var target=MineWork.at(t.e,t.shop,next.cell());var access=MineWork.at(t.e,t.shop,next.stand());
   for(int x=-2;x<=2;x++)for(int y=-1;y<=5;y++)for(int z=-2;z<=2;z++)t.l.setBlock(access.offset(x,y,z),y==-1?Blocks.STONE.defaultBlockState():Blocks.AIR.defaultBlockState(),2);
   t.l.setBlock(target,Blocks.IRON_ORE.defaultBlockState(),2);f.npc.moveTo(access.getX()+.5,access.getY(),access.getZ()+.5);f.npc.setOnGround(true);
   var goal=new ResourceWorkGoal(f.npc,true,()->6000);h.assertTrue(goal.canUse(),"The real mining goal resumes the survey");goal.tick();for(int i=0;i<120&&!t.l.getBlockState(target).isAir();i++)goal.tick();
   var done=MineWork.read(t.l,t.shop);h.assertTrue(t.l.getBlockState(target).isAir(),"The normal goal excavates the actual new ore face");h.assertTrue(done.getList("cargo",Tag.TAG_COMPOUND).stream().map(raw->ItemStack.of((CompoundTag)raw)).filter(stack->stack.is(Items.RAW_IRON)).mapToInt(ItemStack::getCount).sum()==1,"The mined ore is carried, not generated by the planner");
   h.assertTrue(t.s.mineAreas().get(t.shop.id()).lastStep()==25&&t.s.mineAreas().get(t.shop.id()).galleries().stream().anyMatch(g->g.step()==18),"New gallery protection retains the old deepest staircase");
  }finally{f.npc.discard();ResearchV2Town.done(t);}h.succeed();
 }
 @GameTest(template="empty",batch="mine_prospect",timeoutTicks=200)
 public static void oreAlreadyInMineChestDoesNotTriggerUnneededProspecting(GameTestHelper h){
  var f=town(h);var t=f.town;try{LogisticsRoutes.chest(t.l,t.e,t.shop).setItem(0,new ItemStack(Items.RAW_IRON,8));h.assertTrue(!MineProspecting.begin(t.l,t.e,t.shop,f.state),"Stored ore waiting for its porter satisfies the real shortage");}finally{f.npc.discard();ResearchV2Town.done(t);}h.succeed();
 }
 @GameTest(template="empty",batch="mine_prospect",timeoutTicks=200)
 public static void exhaustedSurveyFloorsNeverRepeatAcrossCheckpoints(GameTestHelper h){
  var f=town(h);var t=f.town;try{var state=f.state;
   for(int expected:new int[]{18,12,6,0}){h.assertTrue(MineProspecting.begin(t.l,t.e,t.shop,state),"A remaining shallower survey is available");h.assertTrue(state.getInt("floorStep")==expected,"Survey floors advance once in order");state.putInt("side",MineDrive.DONE);MineWork.write(t.l,t.shop,state);state=MineWork.read(t.l,t.shop);}
   var seen=new HashSet<Integer>(Set.of(0,6,12,18,25));
   while(MineProspecting.begin(t.l,t.e,t.shop,state)){int floor=state.getInt("floorStep");h.assertTrue(floor>=0&&floor<=25&&seen.add(floor),"Refined surveys do not repeat or exceed the unlocked depth");state.putInt("side",MineDrive.DONE);MineWork.write(t.l,t.shop,state);state=MineWork.read(t.l,t.shop);}
   h.assertTrue(seen.size()==26,"All skipped existing landings were surveyed before exhaustion");
   h.assertTrue(!MineProspecting.begin(t.l,t.e,t.shop,state),"Exhausted existing stairs do not repeat old branches or go deeper");
   var area=new MineArea(90,3,5,7);for(int floor=0;floor<=84;floor+=6)for(int side=0;side<2;side++)area=area.with(new MineArea.Gallery(floor,side,4));
   h.assertTrue(area.galleries().size()==30&&area.contains(5,-84-7,7+84,0)&&area.contains(5,-7,7,0),"Many survey branches retain both early and deep protection");
  }finally{f.npc.discard();ResearchV2Town.done(t);}h.succeed();
 }
 @GameTest(template="empty",batch="fine_prospect",timeoutTicks=200)
 public static void unmetOreDemandSurveysEverySkippedUnlockedFloorOnce(GameTestHelper h){
  var f=town(h);var t=f.town;try{var state=f.state;state.putIntArray("surveyedFloors",new int[]{0,6,12,18,25});var seen=new HashSet<Integer>(Set.of(0,6,12,18,25));
   for(int floor=24;floor>=0;floor--){if(seen.contains(floor))continue;
    h.assertTrue(MineProspecting.begin(t.l,t.e,t.shop,state),"Missing ore still requires the skipped floor "+floor);
    h.assertTrue(state.getInt("floorStep")==floor&&seen.add(floor),"Fine survey stays within unlocked stairs and never repeats a row");
    MineWork.write(t.l,t.shop,state);state=MineWork.read(t.l,t.shop);h.assertTrue(MineWork.next(t.l,t.e,t.shop,state).stage()==MineDrive.Stage.EAST,"The saved row resumes as a normal mining drive");state.putInt("side",MineDrive.DONE);
   }
   h.assertTrue(seen.size()==26&&!MineProspecting.begin(t.l,t.e,t.shop,state),"Only a genuinely exhausted set of all unlocked floors ends the bounded search");
  }finally{f.npc.discard();ResearchV2Town.done(t);}h.succeed();
 }
 @GameTest(template="empty",batch="mine_prospect",timeoutTicks=100)
 public static void visibleNeededOreContinuesBetweenCoarseSurveyRows(GameTestHelper h){
  var f=town(h);var t=f.town;try{
   t.s.noteMine(t.shop.id(),new MineArea.Gallery(12,MineDrive.WEST,14));var area=t.s.mineAreas().get(t.shop.id());
   var open=BuildingPlacement.at(t.e,t.shop,-10,-18,19);var ore=BuildingPlacement.at(t.e,t.shop,-10,-18,20);
   t.l.setBlock(ore,Blocks.IRON_ORE.defaultBlockState(),2);t.l.setBlock(open,Blocks.STONE.defaultBlockState(),2);
   var visited=Set.of(0,6,12,18,25);var demand=Set.of(Items.RAW_IRON);
   h.assertTrue(MineOutcrops.floor(t.l,t.e,t.shop,area,25,visited,demand)==-1,"Unexposed ore is not visible through the gallery wall");
   t.l.setBlock(open,Blocks.AIR.defaultBlockState(),2);
   h.assertTrue(MineOutcrops.floor(t.l,t.e,t.shop,area,25,visited,Set.of(Items.RAW_COPPER))==-1,"Only needed raw materials direct the search");
   h.assertTrue(MineOutcrops.floor(t.l,t.e,t.shop,area,12,visited,demand)==-1,"Visible ore never bypasses the working depth limit");
   h.assertTrue(MineOutcrops.floor(t.l,t.e,t.shop,new MineArea(25,3,5,7),25,visited,demand)==-1,"Unexplored caves are not known galleries");
   f.state.putIntArray("surveyedFloors",new int[]{0,6,12,18,25});
   h.assertTrue(MineProspecting.begin(t.l,t.e,t.shop,f.state)&&f.state.getInt("floorStep")==13,"An exposed iron vein starts the skipped row after coarse prospecting is exhausted");
   MineWork.write(t.l,t.shop,f.state);var saved=MineWork.read(t.l,t.shop);h.assertTrue(MineWork.next(t.l,t.e,t.shop,saved).stage()==MineDrive.Stage.EAST&&saved.getInt("floorStep")==13,"Normal excavation resumes this ore-directed branch after reload");
   h.assertTrue(MineOutcrops.floor(t.l,t.e,t.shop,area,25,Set.of(0,6,12,13,18,25),demand)==-1,"Already surveyed rows are not restarted for the same ore");
  }finally{f.npc.discard();ResearchV2Town.done(t);}h.succeed();
 }
 @GameTest(template="empty",batch="mine_prospect",timeoutTicks=100)
 public static void aGalleryAboveAnOpenCaveTurnsBeforeMining(GameTestHelper h){
  var f=town(h);var t=f.town;try{
   var state=f.state;state.putInt("prospectFloor",0);state.putInt("prospectLimit",25);state.putInt("floorStep",0);state.putInt("step",1);state.putInt("side",MineDrive.EAST);state.putInt("cell",0);state.putInt("run",0);state.putString("stage","choose");
   var next=MineWork.next(t.l,t.e,t.shop,state);var target=MineWork.at(t.e,t.shop,next.cell());var floor=BuildingPlacement.at(t.e,t.shop,next.cell().x(),-8,next.cell().z());t.l.setBlock(target,Blocks.STONE.defaultBlockState(),2);t.l.setBlock(floor,Blocks.AIR.defaultBlockState(),2);MineWork.write(t.l,t.shop,state);
   var goal=new ResourceWorkGoal(f.npc,true,()->6000);h.assertTrue(goal.canUse(),"Normal miner resumes the gallery");goal.tick();
   var saved=MineWork.read(t.l,t.shop);h.assertTrue(saved.getInt("side")==MineDrive.WEST&&t.l.getBlockState(target).is(Blocks.STONE),"A missing floor turns the drive before cutting or walking into the cave");
   t.l.setBlock(floor,Blocks.STONE.defaultBlockState(),2);h.assertTrue(MineWork.galleryFloor(t.l,t.e,t.shop,state,next.cell()),"A real dry floor permits normal mining");
  }finally{f.npc.discard();ResearchV2Town.done(t);}h.succeed();
 }
 @GameTest(template="empty",batch="mine_prospect",timeoutTicks=100)
 public static void abandonedUnsupportedBeamReturnsOnlyUnplacedPaidTimber(GameTestHelper h){
  var f=town(h);var t=f.town;try{
   var state=f.state;state.putInt("floorStep",0);state.putInt("step",1);state.putInt("side",0);state.putInt("run",3);state.putInt("cell",4);state.putString("stage","support_place");
   var next=MineDrive.next(MineWork.drive(state),0,MineWork.shape(state));MineWork.chose(state,next);h.assertTrue(next.beam()!=null,"Fixture is a real beam column");state.put("supportTimber",new ListTag());MineTimber.add(state,new ItemStack(Items.BIRCH_LOG));state.putInt("support_fetched",1);
   var foot=MineWork.at(t.e,t.shop,MineWork.beamStand(state));t.l.setBlock(foot.below(),Blocks.AIR.defaultBlockState(),2);var beam=MineWork.at(t.e,t.shop,next.beam().cells().get(0));t.l.setBlock(beam,Blocks.AIR.defaultBlockState(),2);MineWork.write(t.l,t.shop,state);
   var goal=new ResourceWorkGoal(f.npc,true,()->6000);h.assertTrue(goal.canUse(),"Saved beam resumes");goal.tick();var saved=MineWork.read(t.l,t.shop);
   h.assertTrue(saved.getString("stage").equals("choose")&&!saved.contains("beam")&&saved.getList("cargo",Tag.TAG_COMPOUND).stream().map(raw->ItemStack.of((CompoundTag)raw)).filter(st->st.is(Items.BIRCH_LOG)).mapToInt(ItemStack::getCount).sum()==1,"The actual paid log returns to ordinary carried cargo");
   h.assertTrue(saved.getList("cargo",Tag.TAG_COMPOUND).stream().map(raw->ItemStack.of((CompoundTag)raw)).mapToInt(ItemStack::getCount).sum()==1,"No other species or extra logs are added");
   h.assertTrue(t.l.getBlockState(beam).isAir(),"No beam is placed remotely over the cave");
   h.assertTrue(org.villageastra.persistence.WorldJournal.place(t.l,MineWork.beamId(state,state.getUUID("operation"),0),beam,Blocks.AIR.defaultBlockState(),Blocks.BIRCH_LOG.defaultBlockState()),"Fixture commits placement before a stale checkpoint");
   MineTimber.cancel(t.l,state);h.assertTrue(state.getList("cargo",Tag.TAG_COMPOUND).isEmpty(),"Journal-ahead placed wood is not duplicated by cancellation");
  }finally{f.npc.discard();ResearchV2Town.done(t);}h.succeed();
 }
 @GameTest(template="empty",batch="mine_prospect",timeoutTicks=100)
 public static void deeperUpgradeResumesDeepestStairAndNeverBypassesDepthLimit(GameTestHelper h){
  var t=new CompoundTag();t.putInt("prospectFloor",18);t.putInt("prospectLimit",25);t.putInt("extentStep",25);t.putInt("step",19);t.putInt("cell",3);t.putInt("side",1);t.putInt("run",6);t.putInt("galleryOf",18);
  h.assertTrue(MineProspecting.activeFloor(t,12)==12,"A reduced working level still limits the survey");
  h.assertTrue(MineProspecting.activeFloor(t,40)==40&&t.getInt("step")==26&&t.getInt("cell")==0&&!t.contains("prospectFloor")&&!t.contains("galleryOf"),"A higher level resumes below the deepest existing staircase");h.succeed();
 }
}
