package org.villageastra.gametest;
import java.util.*;
import java.nio.file.*;
import net.minecraft.core.BlockPos;
import net.minecraft.gametest.framework.*;
import net.minecraft.nbt.*;
import net.minecraft.world.item.*;
import net.minecraft.world.level.block.Blocks;
import net.minecraftforge.gametest.*;
import org.villageastra.VillageAstra;
import org.villageastra.domain.*;
import org.villageastra.server.*;
import org.villageastra.persistence.*;
import org.villageastra.world.*;
/** AD469: verified parcel sensing may share a tag; reservations and receipts remain authoritative. */
@GameTestHolder(VillageAstra.ID) @PrefixGameTestTemplate(false)
public final class PorterWorkReadCacheGameTests {
 private static CompoundTag job(UUID worker){var t=new CompoundTag();t.putInt("schema",1);t.putUUID("worker",worker);for(var key:List.of("settlement","assignment","id","source","destination"))t.putUUID(key,UUID.randomUUID());t.putString("stage","fetch");var item=new ItemStack(Items.COBBLESTONE,6);item.getOrCreateTag().putString("fixture","original");t.put("item",item.save(new CompoundTag()));return t;}
 @GameTest(template="empty",batch="porter_read_baseline",timeoutTicks=100)
 public static void aHundredUnchangedValidatedParcelReadsShareOneVerification(GameTestHelper h)throws Exception{
  var l=h.getLevel();var worker=UUID.randomUUID();var p=PorterWork.path(l,worker);var original=job(worker);NbtRecord.write(p,original);
  try{long before=PorterWork.inspectReads();int tick=l.getServer().getTickCount();for(int i=0;i<100;i++){var seen=PorterWork.inspect(l,worker);h.assertTrue(seen.equals(original),"Each inspector receives the original valid parcel");seen.getCompound("item").getCompound("tag").putString("fixture","mutated");seen.putString("stage","complete");}long reads=PorterWork.inspectReads()-before;com.mojang.logging.LogUtils.getLogger().info("ZIMBOVILLAGERS_PORTER_READ calls=100 verifiedReads={} actualServerTick={}",reads,tick);h.assertTrue(tick==l.getServer().getTickCount()&&reads==1,"100 unchanged same-real-tick parcel inspectors require one verified read, observed="+reads);}finally{Files.deleteIfExists(p);}h.succeed();
 }
 private static int serial;
 private record Town(net.minecraft.server.level.ServerLevel l,SettlementData.Entry e,Settlement s,Settlement.Building hall,Settlement.Building farm,Settlement.Building lab,ResidentEntity npc,List<net.minecraft.world.level.ChunkPos> held){
  OwnedChestEntity source(){return LogisticsRoutes.chest(l,e,farm);}OwnedChestEntity dest(){return LogisticsRoutes.chest(l,e,lab);}
  void close(){npc.discard();SettlementData.get(l.getServer()).remove(s.id());try{Files.deleteIfExists(PorterWork.path(l,npc.getUUID()));}catch(java.io.IOException ex){throw new IllegalStateException(ex);}PhysicalFixtureChunks.release(l,held);}
 }
 private static Town town(GameTestHelper h){
  var l=h.getLevel();var at=h.absolutePos(BlockPos.ZERO);var center=new BlockPos(at.getX()+3145728+(serial++)*128,110,at.getZ());var held=PhysicalFixtureChunks.force(l,center,-3,40,-3,16);for(var c:held)l.getChunk(c.x,c.z);for(var p:BlockPos.betweenClosed(center.offset(-3,-1,-3),center.offset(40,16,16)))l.setBlock(p,p.getY()<center.getY()?Blocks.STONE.defaultBlockState():Blocks.AIR.defaultBlockState(),2);
  var s=new Settlement(UUID.randomUUID());var hall=new Settlement.Building(UUID.randomUUID(),"town_hall",0,0,0);var farm=new Settlement.Building(UUID.randomUUID(),"farm",12,0,0);var lab=new Settlement.Building(UUID.randomUUID(),"laboratory",24,0,0);for(var b:List.of(hall,farm,lab))s.addBuilding(b);var e=new SettlementData.Entry(s,l.dimension().location().toString(),center);for(var b:List.of(hall,farm,lab))for(var cell:BuildingPlacement.layout(e,b,b.type()).entrySet())l.setBlock(cell.getKey(),BuildingOrders.payable(cell.getValue()),2);
  var home=new Settlement.Home(UUID.randomUUID(),1,8,true);s.addHome(home);var npc=VillageAstra.RESIDENT.get().create(l);var r=new Resident(npc.getUUID(),Resident.Life.CHILD,false,null,null,-1);r.attendSchool(100);r.growUp();s.admit(r,home.id());s.assign(r.id(),Profession.PORTER,hall.id());npc.bind(s.id(),r);npc.setNoAi(true);var atFarm=LogisticsRoutes.position(e,farm);npc.moveTo(atFarm.getX()+1.5,atFarm.getY(),atFarm.getZ()+.5);SettlementData.get(l.getServer()).add(e);var t=new Town(l,e,s,hall,farm,lab,npc,held);t.source().clearContent();t.source().setItem(0,new ItemStack(VillageAstra.RESEARCH_VOLUME.get(),16));t.dest().clearContent();t.dest().setItem(0,new ItemStack(VillageAstra.RESEARCH_VOLUME.get(),1));return t;
 }
 private static CompoundTag planned(Town t,int amount){PorterWork.step(t.npc,new LogisticsRoutes.Route(t.farm,t.lab,new ItemStack(VillageAstra.RESEARCH_VOLUME.get(),amount)),true);return PorterWork.inspect(t.l,t.npc.getUUID());}
 @GameTest(template="empty",batch="porter_read_baseline",timeoutTicks=200)
 public static void aFeasibleActualRouteReusesItsIncomingAndOutgoingJobRead(GameTestHelper h)throws Exception{
  var t=town(h);try{var state=planned(t,1);var p=PorterWork.path(t.l,t.npc.getUUID());NbtRecord.write(p,state);var bytes=Files.readAllBytes(p);long before=PorterWork.inspectReads();int tick=t.l.getServer().getTickCount();var route=LogisticsRoutes.choose(t.l,t.e,t.hall);long reads=PorterWork.inspectReads()-before;h.assertTrue(route!=null&&route.source().id().equals(t.farm.id())&&route.destination().id().equals(t.lab.id())&&route.item().is(VillageAstra.RESEARCH_VOLUME.get())&&route.item().getCount()==5,"Actual feasible planner subtracts the existing incoming and outgoing parcel");h.assertTrue(Arrays.equals(bytes,Files.readAllBytes(p))&&tick==t.l.getServer().getTickCount(),"Actual route planning neither changes job bytes nor advances the real server tick");com.mojang.logging.LogUtils.getLogger().info("ZIMBOVILLAGERS_PORTER_ROUTE verifiedReads={} actualServerTick={} routeAmount=5 unchangedJob=true",reads,tick);h.assertTrue(reads==1,"Actual feasible route requires one verified parcel read, observed="+reads);}finally{t.close();}h.succeed();
 }

 @GameTest(template="empty",batch="porter_read_guards",timeoutTicks=100)
 public static void writesMissingRecordsAndStrictParcelValidationRemainImmediate(GameTestHelper h)throws Exception{
  var l=h.getLevel();var worker=UUID.randomUUID();var p=PorterWork.path(l,worker);var original=job(worker);NbtRecord.write(p,original);PorterWork.inspect(l,worker);var time=Files.getLastModifiedTime(p);long size=Files.size(p);long revision=AtomicRecord.revision(p);
  try{var next=original.copy();next.putString("stage","fetch");next.getCompound("item").putByte("Count",(byte)7);NbtRecord.write(p,next);Files.setLastModifiedTime(p,time);h.assertTrue(Files.size(p)==size&&AtomicRecord.revision(p)>revision&&PorterWork.inspect(l,worker).equals(next),"Same-size same-time authoritative write invalidates now");
   Files.delete(p);var missing=PorterWork.inspect(l,worker);missing.putInt("schema",1);h.assertTrue(PorterWork.inspect(l,worker).isEmpty(),"Deleted job evicts cache and absent copies are independent");NbtRecord.write(p,original);Files.setLastModifiedTime(p,time);h.assertTrue(PorterWork.inspect(l,worker).equals(original),"Signed recreation invalidates immediately");
   var invalid=new ArrayList<CompoundTag>();var bad=original.copy();bad.putInt("schema",2);invalid.add(bad);bad=original.copy();bad.putUUID("worker",UUID.randomUUID());invalid.add(bad);for(var key:List.of("worker","settlement","assignment","id","source","destination")){bad=original.copy();bad.remove(key);invalid.add(bad);}bad=original.copy();bad.putString("stage","idle");invalid.add(bad);for(byte count:new byte[]{0,127}){bad=original.copy();bad.getCompound("item").putByte("Count",count);invalid.add(bad);}
   for(var record:invalid){NbtRecord.write(p,record);for(int retry=0;retry<2;retry++){boolean rejected=false;try{PorterWork.inspect(l,worker);}catch(RuntimeException expected){rejected=true;}h.assertTrue(rejected,"Invalid signed parcel is never cached as a valid or empty job");}}
   NbtRecord.write(p,original);h.assertTrue(PorterWork.inspect(l,worker).equals(original),"A corrected authoritative parcel recovers after refusals");var other=UUID.randomUUID();var sibling=job(other);NbtRecord.write(PorterWork.path(l,other),sibling);h.assertTrue(PorterWork.inspect(l,other).equals(sibling)&&PorterWork.inspect(l,worker).equals(original),"Different owner paths do not share tags");Files.delete(PorterWork.path(l,other));
  }finally{Files.deleteIfExists(p);}h.succeed();
 }
 @GameTest(template="empty",batch="porter_read_guards",timeoutTicks=100)
 public static void everyNextRealTickRevalidatesHiddenChecksumDamage(GameTestHelper h)throws Exception{
  var l=h.getLevel();var worker=UUID.randomUUID();var p=PorterWork.path(l,worker);var original=job(worker);NbtRecord.write(p,original);PorterWork.inspect(l,worker);int tick=l.getServer().getTickCount();
  h.runAtTickTime(2,()->{h.assertTrue(l.getServer().getTickCount()!=tick,"Actual server tick really advances");long before=PorterWork.inspectReads();h.assertTrue(PorterWork.inspect(l,worker).equals(original)&&PorterWork.inspectReads()==before+1,"Next actual tick verifies even unchanged job");try{var time=Files.getLastModifiedTime(p);var bytes=Files.readAllBytes(p);bytes[bytes.length-1]^=1;Files.write(p,bytes);Files.setLastModifiedTime(p,time);}catch(java.io.IOException ex){throw new IllegalStateException(ex);}});
  h.runAtTickTime(4,()->{try{boolean rejected=false;try{PorterWork.inspect(l,worker);}catch(IllegalStateException expected){rejected=true;}h.assertTrue(rejected,"Hidden same-size same-mtime corruption is rejected next actual tick");h.succeed();}finally{try{Files.deleteIfExists(p);}catch(java.io.IOException ex){throw new IllegalStateException(ex);}}});
 }
 @GameTest(template="empty",batch="porter_read_guards",timeoutTicks=200)
 public static void parcelSensingHasBoundedWeakActualServerContexts(GameTestHelper h)throws Exception{
  var l=h.getLevel();var workers=new ArrayList<UUID>();try{for(int i=0;i<257;i++){var worker=UUID.randomUUID();workers.add(worker);NbtRecord.write(PorterWork.path(l,worker),job(worker));PorterWork.inspect(l,worker);}long before=PorterWork.inspectReads();var first=PorterWork.inspect(l,workers.get(0));h.assertTrue(PorterWork.inspectReads()==before+1,"257 owner paths evict the oldest of a bounded 256-entry LRU");
   var field=PorterWork.class.getDeclaredField("PARCEL_READS");field.setAccessible(true);var contexts=(Map<?,?>)field.get(null);h.assertTrue(contexts instanceof WeakHashMap&&contexts.containsKey(l.getServer())&&contexts.keySet().stream().allMatch(k->k instanceof net.minecraft.server.MinecraftServer),"Namespace is weak actual server identity");var cache=(Map<?,?>)contexts.get(l.getServer());h.assertTrue(cache.size()<=256&&cache.keySet().stream().allMatch(k->k instanceof Path p&&p.isAbsolute()&&p.equals(p.normalize())),"Server namespace uses bounded normalized absolute paths");var nether=l.getServer().getLevel(net.minecraft.world.level.Level.NETHER);before=PorterWork.inspectReads();h.assertTrue(nether!=null&&nether.getServer()==l.getServer()&&PorterWork.inspect(nether,workers.get(0)).equals(first)&&PorterWork.inspectReads()==before,"Other dimension of this actual server shares its world-global owner record");
  }finally{for(var worker:workers)Files.deleteIfExists(PorterWork.path(l,worker));}h.succeed();
 }
 @GameTest(template="empty",batch="porter_read_guards",timeoutTicks=100)
 public static void availableIdentityMetadataDetectsExternalSameSizeSameMtimeReplacement(GameTestHelper h)throws Exception{
  var l=h.getLevel();var worker=UUID.randomUUID();var p=PorterWork.path(l,worker);var replacement=p.resolveSibling(worker+".external");var original=job(worker);NbtRecord.write(p,original);PorterWork.inspect(l,worker);var before=Files.readAttributes(p,java.nio.file.attribute.BasicFileAttributes.class);long revision=AtomicRecord.revision(p);
  try{var next=original.copy();next.getCompound("item").putByte("Count",(byte)7);NbtRecord.write(replacement,next);Files.setAttribute(replacement,"basic:creationTime",java.nio.file.attribute.FileTime.fromMillis(before.creationTime().toMillis()+10000));Files.setLastModifiedTime(replacement,before.lastModifiedTime());Files.move(replacement,p,StandardCopyOption.ATOMIC_MOVE,StandardCopyOption.REPLACE_EXISTING);var after=Files.readAttributes(p,java.nio.file.attribute.BasicFileAttributes.class);h.assertTrue(after.size()==before.size()&&after.lastModifiedTime().equals(before.lastModifiedTime())&&AtomicRecord.revision(p)==revision,"External replacement preserves watched revision, size and mtime");h.assertTrue(!after.creationTime().equals(before.creationTime())||!Objects.equals(after.fileKey(),before.fileKey()),"Available identity metadata actually changes");long reads=PorterWork.inspectReads();h.assertTrue(PorterWork.inspect(l,worker).equals(next)&&PorterWork.inspectReads()==reads+1,"Identity metadata forces immediate revalidation");com.mojang.logging.LogUtils.getLogger().info("ZIMBOVILLAGERS_PORTER_IDENTITY creationChanged={} nonNullFileKey={} sameSize=true sameMtime=true unchangedRevision=true",!after.creationTime().equals(before.creationTime()),after.fileKey()!=null);
  }finally{Files.deleteIfExists(p);Files.deleteIfExists(replacement);}h.succeed();
 }
 @GameTest(template="empty",batch="porter_read_guards",timeoutTicks=200)
 public static void realTakeAndPutReceiptsChangeReservationsWithoutChangingCachedJobBytes(GameTestHelper h)throws Exception{
  var t=town(h);try{var state=planned(t,6);var p=PorterWork.path(t.l,t.npc.getUUID());var bytes=Files.readAllBytes(p);long revision=AtomicRecord.revision(p);var item=ItemStack.of(state.getCompound("item"));var take=Settlement.childId(state.getUUID("id"),"take");var put=Settlement.childId(state.getUUID("id"),"put");var matches=(java.util.function.Predicate<ItemStack>)(s->s.is(VillageAstra.RESEARCH_VOLUME.get()));
   h.assertTrue(PorterWork.reserved(t.l,t.e,t.farm.id(),matches,false)==6&&PorterWork.reserved(t.l,t.e,t.lab.id(),matches,true)==6&&PorterWork.cargo(t.l,state).isEmpty(),"Unpaid finite parcel reserves both endpoints and has no paid cargo");h.assertTrue(PorterWork.reserved(t.l,t.e,t.lab.id(),s->s.is(Items.DIAMOND),true)==0&&PorterWork.reserved(t.l,t.e,t.lab.id(),matches,true)==6,"Changing the caller predicate immediately changes reservations with the same cached job");long reads=PorterWork.inspectReads();int tick=t.l.getServer().getTickCount();var held=WorldJournal.takeAmount(t.l,take,LogisticsRoutes.position(t.e,t.farm),0,t.source().getItem(0).copy(),6);h.assertTrue(ItemStack.matches(held,item),"Actual withdrawal pays the original finite six-work parcel");
   h.assertTrue(PorterWork.reserved(t.l,t.e,t.farm.id(),matches,false)==0&&PorterWork.reserved(t.l,t.e,t.lab.id(),matches,true)==6&&ItemStack.matches(PorterWork.cargo(t.l,PorterWork.inspect(t.l,t.npc.getUUID())),item),"Take receipt immediately releases outgoing reservation while retaining paid incoming custody");h.assertTrue(t.source().countItem(VillageAstra.RESEARCH_VOLUME.get())==10&&t.dest().countItem(VillageAstra.RESEARCH_VOLUME.get())==1,"Withdrawal is physical and conserves 10+1+6 works");
   h.assertTrue(WorldJournal.deposit(t.l,put,LogisticsRoutes.position(t.e,t.lab),item),"Actual recorded destination accepts the finite parcel");h.assertTrue(PorterWork.reserved(t.l,t.e,t.lab.id(),matches,true)==0&&PorterWork.cargo(t.l,PorterWork.inspect(t.l,t.npc.getUUID())).isEmpty(),"Put receipt immediately releases incoming reservation and cargo");h.assertTrue(PorterWork.inspectReads()==reads&&AtomicRecord.revision(p)==revision&&Arrays.equals(bytes,Files.readAllBytes(p))&&tick==t.l.getServer().getTickCount(),"Receipt-only changes are live despite unchanged cached NBT, revision and real server tick");
   var noMatch=(java.util.function.Predicate<ItemStack>)(s->s.is(Items.DIAMOND));h.assertTrue(PorterWork.reserved(t.l,t.e,t.lab.id(),noMatch,true)==0,"Caller predicates remain live");NbtRecord.write(p,state);PorterWork.step(t.npc);h.assertTrue(!PorterWork.active(PorterWork.inspect(t.l,t.npc.getUUID()))&&t.source().countItem(VillageAstra.RESEARCH_VOLUME.get())==10&&t.dest().countItem(VillageAstra.RESEARCH_VOLUME.get())==7,"Old fetch checkpoint replays put receipt and closes without duplicating either inventory transition");com.mojang.logging.LogUtils.getLogger().info("ZIMBOVILLAGERS_PORTER_RECEIPTS actualServerTick={} unchangedJob=true takeOutgoing=0 takeIncoming=6 putIncoming=0 cargo=0 conserved=17 replayOnce=true",tick);
  }finally{t.close();}h.succeed();
 }
 @GameTest(template="empty",batch="porter_read_student",timeoutTicks=200)
 public static void parcelCompletionAndPendingCustodyRecheckActualContinuingPupilAdmission(GameTestHelper h){
  var t=town(h);SettlementData.get(t.l.getServer()).remove(t.s.id());h.startSequence().thenWaitUntil(()->h.assertTrue(t.l.isPositionEntityTicking(t.npc.blockPosition()),"Fixture chunk is entity ticking")).thenExecute(()->{h.assertTrue(t.l.getEntity(t.npc.getUUID())==null,"No preexisting body before synchronous registry and body admission");SettlementData.get(t.l.getServer()).add(t.e);h.assertTrue(t.l.addFreshEntity(t.npc)&&t.l.getEntity(t.npc.getUUID())==t.npc,"Canonical pupil is actually added");}).thenWaitUntil(()->h.assertTrue(t.npc.tickCount>0,"Actual pupil ticks")).thenExecute(()->{try{var r=t.s.resident(t.npc.getUUID());h.assertTrue(Population.continuingPupil(t.l,t.e,r),"Unfinished healthy adult course is initially admissible");planned(t,6);h.assertTrue(!Population.continuingPupil(t.l,t.e,r),"Entrusted active parcel excludes school immediately");PorterWork.release(t.l,t.npc.getUUID());h.assertTrue(Population.continuingPupil(t.l,t.e,r),"Same-tick authoritative parcel completion permits course immediately");planned(t,6);PorterWork.step(t.npc);h.assertTrue(PorterWork.cargo(t.l,PorterWork.inspect(t.l,t.npc.getUUID())).getCount()==6,"Second original paid parcel really contains six works");t.s.unassign(r.id());h.assertTrue(CargoCustody.beginReturn(t.npc)&&CargoCustody.pending(t.l.getServer(),r.id()),"Reassignment opens real durable custody of the paid parcel");PorterWork.release(t.l,r.id());h.assertTrue(!Population.continuingPupil(t.l,t.e,r)&&!CargoCustody.mayStartWork(t.npc),"Completed porter tag cannot hide still-pending durable custody from school or work");var at=LogisticsRoutes.position(t.e,t.hall);t.npc.moveTo(at.getX()+1.5,at.getY(),at.getZ()+.5);CargoCustody.returnStep(t.npc,true);CargoCustody.returnStep(t.npc,true);h.assertTrue(!CargoCustody.pending(t.l.getServer(),r.id())&&Population.continuingPupil(t.l,t.e,r)&&LogisticsRoutes.chest(t.l,t.e,t.hall).countItem(VillageAstra.RESEARCH_VOLUME.get())==6&&t.source().countItem(VillageAstra.RESEARCH_VOLUME.get())==10&&t.dest().countItem(VillageAstra.RESEARCH_VOLUME.get())==1,"Actual journal-backed return conserves all 17 works and releases course admission");r.fallIll();h.assertTrue(!Population.continuingPupil(t.l,t.e,r),"Health admission stays live independently of sensing");}finally{t.close();}}).thenSucceed();
 }
}
