package org.villageastra.gametest;
import java.util.*;
import com.mojang.authlib.GameProfile;
import net.minecraft.core.BlockPos;
import net.minecraft.gametest.framework.*;
import net.minecraft.nbt.*;
import net.minecraft.server.level.*;
import net.minecraft.world.item.ItemStack;
import net.minecraftforge.common.util.FakePlayerFactory;
import net.minecraftforge.gametest.*;
import org.villageastra.VillageAstra;
import org.villageastra.domain.*;
import org.villageastra.server.*;
import org.villageastra.world.*;
import org.villageastra.persistence.NbtRecord;
@GameTestHolder(VillageAstra.ID) @PrefixGameTestTemplate(false)
public final class ResidentMarkerGameTests {
 private record Town(ServerLevel l,SettlementData.Entry e,Resident r,ResidentEntity npc,Settlement.Building clinic,ServerPlayer player){}
 private static Town town(GameTestHelper h){var l=h.getLevel();var s=new Settlement(UUID.randomUUID());var c=h.absolutePos(new BlockPos(5,3,5));var hall=new Settlement.Building(UUID.randomUUID(),"town_hall",0,0,0);var clinic=new Settlement.Building(UUID.randomUUID(),"clinic",12,0,0);s.addBuilding(hall);s.addBuilding(clinic);var home=UUID.randomUUID();s.addHome(new Settlement.Home(home,1,8,true));var r=new Resident(UUID.randomUUID(),Resident.Life.ADULT,true,null,null,-1);s.admit(r,home);s.assign(r.id(),Profession.DOCTOR,clinic.id());var e=new SettlementData.Entry(s,l.dimension().location().toString(),c);SettlementData.get(l.getServer()).add(e);for(var b:s.buildings())l.setBlock(LogisticsRoutes.position(e,b),VillageAstra.OWNED_CHEST.get().defaultBlockState(),2);var npc=VillageAstra.RESIDENT.get().create(l);npc.bind(s.id(),r);npc.setNoAi(true);npc.moveTo(c.getX()+12,c.getY()+1,c.getZ(),0,0);l.addFreshEntity(npc);var p=FakePlayerFactory.get(l,new GameProfile(UUID.randomUUID(),"MarkerViewer"));p.setPos(c.getX()+10,c.getY()+1,c.getZ());return new Town(l,e,r,npc,clinic,p);}
 private static CompoundTag row(ServerPlayer p,UUID npc){for(var raw:ResidentMarkers.view(p).getList("residents",Tag.TAG_COMPOUND)){var t=(CompoundTag)raw;if(t.getUUID("id").equals(npc))return t;}return new CompoundTag();}
 private static void board(Town t,CompoundTag q){var b=new CompoundTag();b.putInt("schema",1);var qs=new ListTag();qs.add(q);b.put("quests",qs);NbtRecord.write(Quests.path(t.l,t.e.settlement().id()),b);}
 private static CompoundTag quest(Town t){var q=new CompoundTag();q.putUUID("id",UUID.randomUUID());q.putString("template",Pleas.PLEA);q.putString("state",Quests.OPEN);q.putUUID("giver",t.r.id());q.putLong("deadline",SettlementData.get(t.l.getServer()).clock().ticks()+12000);return q;}
 @GameTest(template="empty") public static void professionAndResourcesFollowRealState(GameTestHelper h){var t=town(h);var before=row(t.player,t.r.id());h.assertTrue(before.getString("profession").equals("doctor")&&!before.getList("items",Tag.TAG_STRING).isEmpty(),"Doctor shows real bandage shortage");LogisticsRoutes.chest(t.l,t.e,t.clinic).setItem(0,new ItemStack(VillageAstra.BANDAGE.get(),64));h.assertTrue(row(t.player,t.r.id()).getList("items",Tag.TAG_STRING).isEmpty(),"Satisfied shortage disappears");t.r.assign(null);h.assertTrue(row(t.player,t.r.id()).getString("profession").equals("unemployed"),"Assignment change refreshes profession without renaming");h.assertTrue(t.npc.getName().getString().equals(t.r.profile().name()),"Personal name survives");t.npc.discard();h.succeed();}
 @GameTest(template="empty") public static void questMarkIsPrivateAndUsesAcceptanceAuthority(GameTestHelper h){var t=town(h);var other=FakePlayerFactory.get(t.l,new GameProfile(UUID.randomUUID(),"OtherViewer"));other.setPos(t.player.position());var q=quest(t);q.putUUID("reserved",t.player.getUUID());board(t,q);h.assertTrue(row(t.player,t.r.id()).getBoolean("quest")&&!row(other,t.r.id()).getBoolean("quest"),"Reserved quest is shown only to its intended player");var given=new ListTag();given.add(NbtUtils.createUUID(t.player.getUUID()));q.put("given_up",given);board(t,q);h.assertTrue(!row(t.player,t.r.id()).getBoolean("quest"),"Abandoned quest cannot be advertised again");q.remove("given_up");q.putString("state",Quests.TAKEN);q.putUUID("owner",t.player.getUUID());board(t,q);h.assertTrue(!row(t.player,t.r.id()).getBoolean("quest")&&!row(other,t.r.id()).getBoolean("quest"),"Already taken quest has no invitation");q.putString("state",Quests.OPEN);q.putLong("deadline",0);board(t,q);h.assertTrue(!row(t.player,t.r.id()).getBoolean("quest"),"Expired quest has no invitation");t.npc.discard();h.succeed();}
 @GameTest(template="empty",timeoutTicks=40) public static void reloadAndLeavingRangeDoNotLeaveStaleMarkers(GameTestHelper h){var t=town(h);var saved=new CompoundTag();t.npc.saveWithoutId(saved);var id=t.r.id();t.npc.discard();h.runAfterDelay(2,()->{var loaded=VillageAstra.RESIDENT.get().create(t.l);loaded.load(saved);t.l.addFreshEntity(loaded);h.assertTrue(row(t.player,id).getString("profession").equals("doctor"),"Reload derives current profession from settlement");t.player.setPos(t.player.getX()+100,t.player.getY(),t.player.getZ());h.assertTrue(row(t.player,id).isEmpty(),"Leaving range removes resident from the full replacement snapshot");loaded.discard();h.succeed();});}
 @GameTest(template="empty") public static void minerShowsToolShortageAtSharedHall(GameTestHelper h){var t=town(h);var mine=new Settlement.Building(UUID.randomUUID(),"mine",24,0,0);t.e.settlement().addBuilding(mine);t.e.settlement().assign(t.r.id(),Profession.MINER,mine.id());var need=row(t.player,t.r.id());h.assertTrue(need.getList("items",Tag.TAG_STRING).stream().anyMatch(i->i.getAsString().equals("minecraft:stone_pickaxe")),"Miner advertises the missing shared-hall tool");LogisticsRoutes.chest(t.l,t.e,Workshops.hall(t.e)).setItem(0,new ItemStack(net.minecraft.world.item.Items.STONE_PICKAXE));h.assertTrue(row(t.player,t.r.id()).getList("items",Tag.TAG_STRING).isEmpty(),"Tool request disappears when the hall has it");t.npc.discard();h.succeed();}

}
