package org.villageastra.gametest;
import java.util.*;
import net.minecraft.core.BlockPos;
import net.minecraft.gametest.framework.*;
import net.minecraft.nbt.*;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.block.Blocks;
import net.minecraftforge.gametest.*;
import org.villageastra.VillageAstra;
import org.villageastra.domain.*;
import org.villageastra.server.*;
import org.villageastra.world.*;
import org.villageastra.persistence.*;
/** AD472: isolated, monotonic full-period village-clock service fixtures, not natural growth. */
@GameTestHolder(VillageAstra.ID) @PrefixGameTestTemplate(false)
public final class ScienceCustodyGameTests {
 private static int serial;
 private static final long W=ScienceBalance.WORK_TICKS;
 private record Town(net.minecraft.server.level.ServerLevel l,SettlementData.Entry e,Settlement s,Settlement.Building hall,Settlement.Building lab,Resident r,ResidentEntity npc,List<net.minecraft.world.level.ChunkPos> held){
  void close(){npc.discard();SettlementData.get(l.getServer()).remove(s.id());BuildingLevels.forgetBest(s.id());PhysicalFixtureChunks.release(l,held);}
 }
 private static Town town(GameTestHelper h){var l=h.getLevel();var center=h.absolutePos(BlockPos.ZERO).offset(3970048+(serial++)*128,110,0);var held=PhysicalFixtureChunks.force(l,center,-3,62,-3,18);for(var c:held)l.getChunk(c.x,c.z);for(var p:BlockPos.betweenClosed(center.offset(-3,-1,-3),center.offset(62,18,18)))l.setBlock(p,p.getY()<center.getY()?Blocks.STONE.defaultBlockState():Blocks.AIR.defaultBlockState(),2);
  var s=new Settlement(UUID.randomUUID());var hall=new Settlement.Building(UUID.randomUUID(),"town_hall",0,0,0);var lab=new Settlement.Building(UUID.randomUUID(),"laboratory",30,0,0);s.addBuilding(hall);s.addBuilding(lab);s.addHome(new Settlement.Home(UUID.randomUUID(),1,8,true));var e=new SettlementData.Entry(s,l.dimension().location().toString(),center);ResearchV2Town.lay(l,e,hall,"town_hall");ResearchV2Town.lay(l,e,lab,"laboratory");var r=new Resident(UUID.randomUUID(),Resident.Life.ADULT,true,null,null,-1);s.admit(r,s.homes().iterator().next().id());s.assign(r.id(),Profession.PORTER,hall.id());var npc=VillageAstra.RESIDENT.get().create(l);npc.bind(s.id(),r);npc.setNoAi(true);var at=LogisticsRoutes.position(e,hall);npc.moveTo(at.getX()+1.5,at.getY(),at.getZ()+.5);return new Town(l,e,s,hall,lab,r,npc,held);
 }
 private static void ready(GameTestHelper h,java.util.function.Consumer<Town> run){var t=town(h);h.startSequence().thenWaitUntil(()->h.assertTrue(t.l.isPositionEntityTicking(t.npc.blockPosition()),"Paid-cargo body chunk really ticks")).thenExecute(()->{h.assertTrue(t.l.getEntity(t.r.id())==null,"No competing body before admission");SettlementData.get(t.l.getServer()).add(t.e);h.assertTrue(t.l.addFreshEntity(t.npc)&&t.l.getEntity(t.r.id())==t.npc,"Canonical actual body admitted once");}).thenWaitUntil(()->h.assertTrue(t.npc.tickCount>0,"Actual body has physically ticked")).thenExecute(()->{try{run.accept(t);}finally{t.close();}}).thenSucceed();}
 private static long now(Town t){return SettlementData.get(t.l.getServer()).clock().ticks();}
 private static long elapse(Town t,long ticks){var clock=SettlementData.get(t.l.getServer()).clock();for(long i=0;i<ticks;i++)if(!clock.advance(true,false))throw new IllegalStateException("Fixture clock did not advance");return clock.ticks();}
 private static void parcel(GameTestHelper h,Town t){t.s.assign(t.r.id(),Profession.PORTER,t.hall.id());var stock=LogisticsRoutes.chest(t.l,t.e,t.hall);stock.setItem(0,new ItemStack(VillageAstra.RESEARCH_VOLUME.get(),2));var route=new LogisticsRoutes.Route(t.hall,t.lab,new ItemStack(VillageAstra.RESEARCH_VOLUME.get(),2));PorterWork.step(t.npc,route,false);PorterWork.step(t.npc);h.assertTrue(PorterWork.cargo(t.l,PorterWork.inspect(t.l,t.r.id())).getCount()==2&&stock.countItem(VillageAstra.RESEARCH_VOLUME.get())==0,"Two finite works are actually paid into a durable porter parcel");t.s.assign(t.r.id(),Profession.SCIENTIST,t.lab.id());}
 private static void returned(GameTestHelper h,Town t){CargoCustody.returnStep(t.npc,true);CargoCustody.returnStep(t.npc,true);h.assertTrue(!CargoCustody.pending(t.l.getServer(),t.r.id())&&LogisticsRoutes.chest(t.l,t.e,t.hall).countItem(VillageAstra.RESEARCH_VOLUME.get())==2,"Actual return restores exactly the original two paid works");}
 private static CompoundTag seat(Town t){return NbtRecord.read(ScienceWorks.path(t.l,t.lab.id())).getList("seats",Tag.TAG_COMPOUND).getCompound(0);}
 @GameTest(template="empty",batch="science_custody_baseline",timeoutTicks=200)
 public static void actualPendingPaidCargoCannotWriteANewFullPeriodScientificWork(GameTestHelper h){ready(h,t->{parcel(h,t);h.assertTrue(CargoCustody.beginReturn(t.npc)&&CargoCustody.pending(t.l.getServer(),t.r.id())&&!CargoCustody.mayStartWork(t.npc),"Real pending paid cargo refuses work admission");ScienceWorks.advance(t.l,t.e,now(t));h.assertTrue(!seat(t).hasUUID("worker")&&ScienceWorks.seated(t.l,t.e)==0&&ScienceWorks.seat(t.l,t.e,t.r.id())==-1&&!ScienceWorks.status(t.l,t.e,t.r.id()).equals("science_writing"),"Pending new scientist cannot occupy a free place or advertise writing");int written=ScienceWorks.advance(t.l,t.e,elapse(t,W));int books=LogisticsRoutes.chest(t.l,t.e,t.lab).countItem(VillageAstra.RESEARCH_VOLUME.get());com.mojang.logging.LogUtils.getLogger().info("ZIMBOVILLAGERS_SCIENCE_CUSTODY_ORACLE pending=true paidCargo=2 fullWorkTicks={} written={} books={} bodyTicks={} actualClock={}",W,written,books,t.npc.tickCount,now(t));returned(h,t);h.assertTrue(written==0&&books==0,"A pending actual paid-cargo scientist must not earn or write during the full return interval; observed="+written);ScienceWorks.advance(t.l,t.e,now(t));h.assertTrue(ScienceWorks.advance(t.l,t.e,elapse(t,W-1))==0&&ScienceWorks.advance(t.l,t.e,elapse(t,1))==1,"The returned new scientist pays the full unchanged period");});}
 private static void forgetCargo(Town t){try{var f=CargoCustody.class.getDeclaredField("CACHE");f.setAccessible(true);var caches=(Map<?,?>)f.get(null);var owners=(Map<?,?>)caches.get(t.l.getServer());if(owners!=null)owners.remove(t.r.id());}catch(ReflectiveOperationException ex){throw new IllegalStateException(ex);}}
 private static void running(GameTestHelper h,Town t){t.s.assign(t.r.id(),Profession.SCIENTIST,t.lab.id());h.assertTrue(ScienceWorks.advance(t.l,t.e,now(t))==0,"Initial seat has no free output");}
 @GameTest(template="empty",batch="science_custody_running",timeoutTicks=200)
 public static void beginImmediatelyKeepsTheEarnedHalfAndRepeatDoesNotMoveItsBoundary(GameTestHelper h){ready(h,t->{running(h,t);elapse(t,W/2);parcel(h,t);long boundary=now(t);h.assertTrue(CargoCustody.beginReturn(t.npc),"Actual custody opens");var start=CargoCustody.inspect(t.l.getServer(),t.r.id());var paused=seat(t);h.assertTrue(start.getLong("startedAt")==boundary&&paused.getLong("ticks")==W/2&&paused.getLong("since")==-1&&paused.getUUID("worker").equals(t.r.id())&&paused.getInt("n")==0&&paused.getUUID("custody").equals(start.getUUID("id")),"BEGIN immediately pauses exactly the held seat, retaining earned ticks, worker and sequence");h.assertTrue(ScienceWorks.seated(t.l,t.e)==0&&ScienceWorks.seat(t.l,t.e,t.r.id())==-1&&ScienceWorks.status(t.l,t.e,t.r.id()).equals("returning_cargo"),"The retained paused worker is not exposed as a currently working desk");elapse(t,173);h.assertTrue(CargoCustody.beginReturn(t.npc)&&CargoCustody.inspect(t.l.getServer(),t.r.id()).getLong("startedAt")==boundary&&seat(t).getLong("ticks")==W/2,"Repeated BEGIN retains the original boundary and counter");h.assertTrue(ScienceWorks.advance(t.l,t.e,elapse(t,W))==0&&seat(t).getLong("ticks")==W/2,"A full pending period adds no scientific work or ticks");returned(h,t);long completed=now(t);h.assertTrue(CargoCustody.inspect(t.l.getServer(),t.r.id()).getLong("completedAt")==completed,"Real completion signs its actual village clock");ScienceWorks.advance(t.l,t.e,now(t));h.assertTrue(ScienceWorks.advance(t.l,t.e,elapse(t,W/2-1))==0&&ScienceWorks.advance(t.l,t.e,elapse(t,1))==1,"The preserved half finishes only after the other full half is paid");h.assertTrue(seat(t).getInt("n")==1&&ScienceWorks.advance(t.l,t.e,now(t))==0,"The original output sequence advances once");});}
 @GameTest(template="empty",batch="science_custody_short",timeoutTicks=200)
 public static void aWholeShortReturnBetweenSciencePassesKeepsOnlyActualWorkingIntervals(GameTestHelper h){ready(h,t->{running(h,t);elapse(t,W/2);parcel(h,t);CargoCustody.beginReturn(t.npc);elapse(t,W/3);returned(h,t);h.assertTrue(ScienceWorks.advance(t.l,t.e,elapse(t,W/2-1))==0,"No science pass during custody: signed completion preserves the post-return working interval but excludes all cargo time");h.assertTrue(ScienceWorks.advance(t.l,t.e,elapse(t,1))==1&&seat(t).getInt("n")==1,"Exactly two real worked halves produce one work");});}
 @GameTest(template="empty",batch="science_custody_recovery",timeoutTicks=200)
 public static void aMissedBeginHookIsRecoveredEvenAfterCompletionBeforeReading(GameTestHelper h){ready(h,t->{running(h,t);elapse(t,W/2);var before=NbtRecord.read(ScienceWorks.path(t.l,t.lab.id()));parcel(h,t);CargoCustody.beginReturn(t.npc);var id=CargoCustody.inspect(t.l.getServer(),t.r.id()).getUUID("id");NbtRecord.write(ScienceWorks.path(t.l,t.lab.id()),before); // Crash boundary: durable BEGIN survived but the following science write did not.
  elapse(t,W);returned(h,t);forgetCargo(t);h.assertTrue(ScienceWorks.advance(t.l,t.e,elapse(t,W/2-1))==0,"Fresh signed custody read recovers a missed pause even when cargo already returned");var recovered=seat(t);h.assertTrue(recovered.getUUID("custody").equals(id)&&recovered.getLong("ticks")==W/2&&!recovered.getBoolean("custodyPaused")&&!recovered.getBoolean("custodyLegacy"),"Recovery retains the exact earned half with a durable replay marker");h.assertTrue(ScienceWorks.advance(t.l,t.e,elapse(t,1))==1,"Recovered place still pays the remaining full half");var stable=NbtRecord.read(ScienceWorks.path(t.l,t.lab.id()));forgetCargo(t);CargoCustody.recover(t.l.getServer());h.assertTrue(ScienceWorks.advance(t.l,t.e,now(t))==0&&NbtRecord.read(ScienceWorks.path(t.l,t.lab.id())).equals(stable)&&LogisticsRoutes.chest(t.l,t.e,t.hall).countItem(VillageAstra.RESEARCH_VOLUME.get())==2,"Reload and replay duplicate neither cargo nor scientific output or progress");});}
 @GameTest(template="empty",batch="science_custody_legacy",timeoutTicks=200)
 public static void legacyWithoutStartedAtPreservesOldAccountingAndMarksTheFirstObservation(GameTestHelper h){ready(h,t->{running(h,t);elapse(t,W/2);var before=NbtRecord.read(ScienceWorks.path(t.l,t.lab.id()));parcel(h,t);CargoCustody.beginReturn(t.npc);var cargo=CargoCustody.inspect(t.l.getServer(),t.r.id());cargo.remove("startedAt");var file=t.l.getServer().getWorldPath(net.minecraft.world.level.storage.LevelResource.ROOT).resolve("data/astra-custody").resolve(t.r.id()+".bin");NbtRecord.write(file,cargo);forgetCargo(t);NbtRecord.write(ScienceWorks.path(t.l,t.lab.id()),before);long observed=elapse(t,W/4);h.assertTrue(ScienceWorks.advance(t.l,t.e,observed)==0,"Legacy first observation retains its previously counted interval");var migrated=seat(t);h.assertTrue(migrated.getBoolean("custodyLegacy")&&migrated.getLong("custodyObservedAt")==observed&&migrated.getLong("ticks")==3*W/4&&migrated.getLong("since")==-1,"Explicit durable legacy marker preserves old accrued 3/4; it does not claim the unknowable original boundary");forgetCargo(t);h.assertTrue(ScienceWorks.advance(t.l,t.e,elapse(t,W))==0&&seat(t).getLong("ticks")==3*W/4&&seat(t).getLong("custodyObservedAt")==observed,"Repeated/reloaded pending legacy custody stops further accrual without resetting earned progress");returned(h,t);ScienceWorks.advance(t.l,t.e,now(t));h.assertTrue(ScienceWorks.advance(t.l,t.e,elapse(t,W/4-1))==0&&ScienceWorks.advance(t.l,t.e,elapse(t,1))==1,"Only the preserved legacy remainder is earned after actual return");});}
 @GameTest(template="empty",batch="science_custody_earned",timeoutTicks=200)
 public static void aFullyEarnedUnwrittenWorkIsRetainedButCannotBeIssuedDuringCustody(GameTestHelper h){ready(h,t->{running(h,t);elapse(t,W);parcel(h,t);CargoCustody.beginReturn(t.npc);h.assertTrue(seat(t).getLong("ticks")==W&&seat(t).getInt("n")==0&&ScienceWorks.advance(t.l,t.e,elapse(t,W))==0,"An already earned work and its sequence remain intact, but pending cargo cannot issue it");returned(h,t);h.assertTrue(ScienceWorks.advance(t.l,t.e,now(t))==1&&seat(t).getInt("n")==1&&ScienceWorks.advance(t.l,t.e,now(t))==0,"Returning releases the one fully earned work once, without a free second period");});}
 @GameTest(template="empty",batch="science_custody_policy",timeoutTicks=200)
 public static void unchangedIllnessAndMissingBodyDoNotIntroduceANewScienceTimerPolicy(GameTestHelper h){ready(h,t->{running(h,t);t.r.fallIll();t.npc.discard();h.assertTrue(!CargoCustody.pending(t.l.getServer(),t.r.id())&&ScienceWorks.advance(t.l,t.e,elapse(t,W-1))==0&&ScienceWorks.advance(t.l,t.e,elapse(t,1))==1,"Without custody, the existing illness and absent-body village-clock service semantics remain unchanged at full WORK_TICKS");});}
 @GameTest(template="empty",batch="science_custody_policy",timeoutTicks=200)
 public static void aMissingChestStillAccumulatesAndPaysOnlyWhenTheRealChestReturns(GameTestHelper h){ready(h,t->{running(h,t);var pos=LogisticsRoutes.position(t.e,t.lab);var state=t.l.getBlockState(pos);h.assertTrue(LogisticsRoutes.chest(t.l,t.e,t.lab)!=null,"Actual laboratory chest stands");t.l.setBlock(pos,Blocks.AIR.defaultBlockState(),2);h.assertTrue(LogisticsRoutes.chest(t.l,t.e,t.lab)==null&&ScienceWorks.advance(t.l,t.e,elapse(t,W))==0,"Missing chest postpones existing scientific delivery");t.l.setBlock(pos,state,2);h.assertTrue(ScienceWorks.advance(t.l,t.e,now(t))==1&&ScienceWorks.advance(t.l,t.e,now(t))==0,"Existing catch-up and output replay semantics are retained");});}
 @GameTest(template="empty",batch="science_custody_recovery",timeoutTicks=200)
 public static void twoConsecutiveReturnsWithoutASciencePassKeepTheWorkedGap(GameTestHelper h){ready(h,t->{running(h,t);elapse(t,W/4);parcel(h,t);CargoCustody.beginReturn(t.npc);var first=CargoCustody.inspect(t.l.getServer(),t.r.id()).getUUID("id");elapse(t,W/3);returned(h,t);elapse(t,W/4);parcel(h,t);CargoCustody.beginReturn(t.npc);var second=CargoCustody.inspect(t.l.getServer(),t.r.id()).getUUID("id");h.assertTrue(!first.equals(second)&&seat(t).getLong("ticks")==W/2&&seat(t).getUUID("custody").equals(second),"A new durable BEGIN first recovers the previous completed interval: two worked quarters survive, neither return interval counts");elapse(t,W/3);returned(h,t);h.assertTrue(ScienceWorks.advance(t.l,t.e,elapse(t,W/2-1))==0&&ScienceWorks.advance(t.l,t.e,elapse(t,1))==1&&seat(t).getInt("n")==1,"The remaining full half produces one work after two distinct paid-cargo returns");});}
 @GameTest(template="empty",batch="science_custody_full_chest",timeoutTicks=200)
 public static void anAlreadyFullStoppedSeatDoesNotRestartDuringOrAfterCargoUntilItsChestCanAcceptTheEarnedWork(GameTestHelper h){ready(h,t->{running(h,t);parcel(h,t);var chest=LogisticsRoutes.chest(t.l,t.e,t.lab);for(int i=0;i<chest.getContainerSize();i++)chest.setItem(i,new ItemStack(net.minecraft.world.item.Items.COBBLESTONE,64));h.assertTrue(ScienceWorks.advance(t.l,t.e,elapse(t,3*W))==0&&seat(t).getBoolean("full")&&seat(t).getLong("since")==-1&&seat(t).getLong("ticks")==W,"Historical full chest caps one earned work and stops its clock");CargoCustody.beginReturn(t.npc);h.assertTrue(seat(t).getBoolean("full")&&seat(t).getLong("since")==-1&&seat(t).getLong("ticks")==W&&ScienceWorks.seat(t.l,t.e,t.r.id())==-1&&ScienceWorks.seated(t.l,t.e)==0,"BEGIN retains the existing stopped full seat without exposing a working desk");h.assertTrue(ScienceWorks.advance(t.l,t.e,elapse(t,W))==0,"Pending/full seat accrues and issues nothing");returned(h,t);h.assertTrue(ScienceWorks.advance(t.l,t.e,now(t))==0&&ScienceWorks.advance(t.l,t.e,elapse(t,W))==0&&seat(t).getLong("since")==-1&&seat(t).getLong("ticks")==W&&seat(t).getInt("n")==0&&ScienceWorks.status(t.l,t.e,t.r.id()).equals("science_chest_full"),"Return alone cannot restart the full clock; no paused/full interval is charged");chest.setItem(0,ItemStack.EMPTY);h.assertTrue(ScienceWorks.advance(t.l,t.e,now(t))==1&&seat(t).getInt("n")==1&&seat(t).getLong("since")==now(t),"The original earned work is issued once only when the real chest can accept it");h.assertTrue(ScienceWorks.advance(t.l,t.e,elapse(t,W-1))==0&&ScienceWorks.advance(t.l,t.e,elapse(t,1))==1,"After real delivery, the next work still pays a complete fresh period");});}
 @GameTest(template="empty",batch="science_custody_death",timeoutTicks=200)
 public static void completedDeathCustodyCannotRestartTheDeadScientistsClock(GameTestHelper h){ready(h,t->{running(h,t);elapse(t,W/2);parcel(h,t);h.assertTrue(t.npc.hurt(t.l.damageSources().genericKill(),1000)&&!t.r.alive(),"Actual physical death closes the resident and opens durable death custody");var cargo=CargoCustody.inspect(t.l.getServer(),t.r.id());h.assertTrue(cargo.getBoolean("dead")&&!cargo.getBoolean("complete")&&seat(t).getLong("ticks")==W/2&&seat(t).getLong("since")==-1,"Death BEGIN retains the exact earned half before finite cargo completion");elapse(t,W/3);CargoCustody.tick(t.l.getServer());cargo=CargoCustody.inspect(t.l.getServer(),t.r.id());h.assertTrue(cargo.getBoolean("complete")&&cargo.getLong("completedAt")==now(t),"Actual finite death custody completes at its signed village clock");var pile=(net.minecraft.world.Container)t.l.getBlockEntity(BlockPos.of(cargo.getList("drops",Tag.TAG_COMPOUND).getCompound(0).getLong("pos")));h.assertTrue(pile!=null&&pile.countItem(VillageAstra.RESEARCH_VOLUME.get())==2&&LogisticsRoutes.chest(t.l,t.e,t.hall).countItem(VillageAstra.RESEARCH_VOLUME.get())==0,"Only the original two paid works remain in the actual death cargo container");int written=ScienceWorks.advance(t.l,t.e,elapse(t,W));var kept=seat(t);com.mojang.logging.LogUtils.getLogger().info("ZIMBOVILLAGERS_SCIENCE_CUSTODY_DEATH dead=true complete=true earnedHalf={} written={} retainedTicks={} sequence={}",W/2,written,kept.getLong("ticks"),kept.getInt("n"));h.assertTrue(written==0&&kept.getLong("ticks")==W/2&&kept.getLong("since")==-1&&kept.getInt("n")==0&&!kept.hasUUID("worker"),"Completed death custody never resumes the dead clock: no work may be charged after death, and earned half/sequence survive");h.assertTrue(ScienceWorks.advance(t.l,t.e,elapse(t,W))==0&&pile.countItem(VillageAstra.RESEARCH_VOLUME.get())==2,"Later service/recovery cannot duplicate scientific output or finite death cargo");});}
}
