package org.villageastra.gametest;
import java.util.*;
import net.minecraft.core.BlockPos;
import net.minecraft.gametest.framework.*;
import net.minecraft.nbt.*;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.entity.animal.Wolf;
import net.minecraft.world.item.*;
import net.minecraft.world.level.block.Blocks;
import net.minecraftforge.gametest.*;
import org.villageastra.VillageAstra;
import org.villageastra.domain.*;
import org.villageastra.server.*;
import org.villageastra.world.*;
/** AD476: a free wolf does not replace warehouse couriers before it has usable paid transport. */
@GameTestHolder(VillageAstra.ID) @PrefixGameTestTemplate(false)
public final class WarehouseReliefGameTests {
 private static int serial;
 record Town(ServerLevel l,SettlementData.Entry e,Settlement s,Settlement.Building hall,Settlement.Building store,Settlement.Building mine,Settlement.Building kennel,Wolf wolf,ResidentEntity porter,List<net.minecraft.world.level.ChunkPos> held){
  void close(){com.mojang.logging.LogUtils.getLogger().info("ZIMBOVILLAGERS_WAREHOUSE_RELIEF sceneClose=true center={} held={}",e.center(),held);VillageWolves.releaseDog(l,wolf.getUUID());for(var c:WarehouseCarts.carts(l,store))c.discard();wolf.discard();porter.discard();for(var r:s.residents())if(l.getEntity(r.id()) instanceof ResidentEntity body)body.discard();CartWolves.forget(s.id());SettlementData.get(l.getServer()).remove(s.id());WarehouseTrips.forget(l.getServer());BuildingLevels.forgetBest(s.id());PhysicalFixtureChunks.release(l,held);}
 }
 private static Town town(GameTestHelper h){return town(h,true);}
 private static Town town(GameTestHelper h,boolean near){return town(h,near,false);}
 static Town town(GameTestHelper h,boolean near,boolean cardinal){
  var l=h.getLevel();var at=h.absolutePos(BlockPos.ZERO);var center=new BlockPos(at.getX()+5242880+(serial++)*128,110,at.getZ());var held=PhysicalFixtureChunks.force(l,center,-4,82,-4,28);for(var c:held)l.getChunk(c.x,c.z);for(var p:BlockPos.betweenClosed(center.offset(-4,-1,-4),center.offset(82,22,28)))l.setBlock(p,p.getY()<center.getY()?Blocks.STONE.defaultBlockState():Blocks.AIR.defaultBlockState(),2);
  com.mojang.logging.LogUtils.getLogger().info("ZIMBOVILLAGERS_WAREHOUSE_RELIEF sceneCreated=true serial={} absolute={} center={} held={}",serial-1,at,center,held);var s=new Settlement(UUID.randomUUID());var hall=new Settlement.Building(UUID.randomUUID(),"town_hall",0,0,0);var store=new Settlement.Building(UUID.randomUUID(),"warehouse",12,0,0);var mine=new Settlement.Building(UUID.randomUUID(),"mine",44,0,0);var yard=new Settlement.Building(UUID.randomUUID(),"livestock",54,0,0);var kennel=new Settlement.Building(UUID.randomUUID(),VillageWolves.TYPE,72,0,0);for(var b:List.of(hall,store,mine,yard,kennel))s.addBuilding(b);s.linkAnnex(kennel.id(),yard.id());var home=new Settlement.Home(UUID.randomUUID(),1,16,true);s.addHome(home);var e=new SettlementData.Entry(s,l.dimension().location().toString(),center);SettlementData.get(l.getServer()).add(e);
  ResearchV2Town.lay(l,e,hall,"town_hall");ResearchV2Town.lay(l,e,store,"warehouse");for(int n=2;n<=6;n++)s.raiseBuildingLevel(store.id(),n);store=s.buildings().stream().filter(WarehouseStore::is).findFirst().orElseThrow();ResearchV2Town.lay(l,e,store,BuildingTiers.layoutId("warehouse",6));for(var b:List.of(mine,kennel))l.setBlock(LogisticsRoutes.position(e,b),VillageAstra.OWNED_CHEST.get().defaultBlockState(),2);WarehouseStorage.ensure(l,e,store);var research=BookResearch.inspect(l,e);var done=research.getList("legacyDone",Tag.TAG_STRING);for(int n=1;n<=6;n++)for(var id:BuildingTiers.research("warehouse",n))done.add(StringTag.valueOf(id));research.put("legacyDone",done);BookResearch.store(l,e,research);ResearchKnobs.forget(s.id());
  var builder=new Resident(UUID.randomUUID(),Resident.Life.ADULT,false,null,null,-1);s.admit(builder,home.id());s.assign(builder.id(),Profession.BUILDER,hall.id());var porter=VillageAstra.RESIDENT.get().create(l);var r=new Resident(porter.getUUID(),Resident.Life.ADULT,false,null,null,-1);s.admit(r,home.id());s.assign(r.id(),Profession.PORTER,store.id());porter.bind(s.id(),r);porter.setNoAi(false);porter.goalSelector.removeAllGoals(g->!(g instanceof ResidentDoorGoal));porter.targetSelector.removeAllGoals(g->true);var stockPos=LogisticsRoutes.position(e,store);BlockPos stand=null;for(var p:BlockPos.betweenClosed(stockPos.offset(-2,0,-2),stockPos.offset(3,1,2))){var point=net.minecraft.world.phys.Vec3.atBottomCenterOf(p);if(point.distanceToSqr(new net.minecraft.world.phys.Vec3(stockPos.getX()+1.5,stockPos.getY(),stockPos.getZ()+.5))<=6.25&&l.getBlockState(p.below()).isFaceSturdy(l,p.below(),net.minecraft.core.Direction.UP)&&l.noCollision(porter,porter.getBoundingBox().move(point.subtract(porter.position())))){stand=p.immutable();break;}}h.assertTrue(stand!=null,"Supported free warehouse courier admission cell exists");porter.moveTo(stand.getX()+.5,stand.getY(),stand.getZ()+.5);
  var wolf=net.minecraft.world.entity.EntityType.WOLF.create(l);wolf.setNoAi(true);wolf.moveTo(center.getX()+40.5,110,center.getZ()+2.5);if(near){BlockPos safe=null;var bay=WarehouseStore.at(e,store,WarehouseStore.B1);for(var p:cardinal?List.of(bay.offset(1,0,0),bay.offset(0,0,-1),bay.offset(0,0,1),bay.offset(-1,0,0)):BlockPos.betweenClosed(bay.offset(-2,0,-2),bay.offset(2,1,2))){var point=net.minecraft.world.phys.Vec3.atBottomCenterOf(p);if(point.distanceToSqr(net.minecraft.world.phys.Vec3.atBottomCenterOf(bay))<=9&&l.getBlockState(p.below()).isFaceSturdy(l,p.below(),net.minecraft.core.Direction.UP)&&l.noCollision(wolf,wolf.getBoundingBox().move(point.subtract(wolf.position())))){safe=p.immutable();break;}}h.assertTrue(safe!=null,"Supported collision-free initial wolf admission near real bay");wolf.moveTo(safe.getX()+.5,safe.getY(),safe.getZ()+.5);}h.assertTrue(l.getBlockState(wolf.blockPosition().below()).isFaceSturdy(l,wolf.blockPosition().below(),net.minecraft.core.Direction.UP)&&l.noCollision(wolf,wolf.getBoundingBox()),"Initial wolf admission before add has solid support and its full free bounding box");h.assertTrue(VillageWolves.enlist(l,e,wolf,kennel),"Actual kennel registry admits the fixture wolf");LogisticsRoutes.chest(l,e,kennel).setItem(0,new ItemStack(Items.BEEF,1));SettlementData.get(l.getServer()).remove(s.id());return new Town(l,e,s,hall,store,mine,kennel,wolf,porter,held);
 }
 @GameTest(template="empty",batch="warehouse_relief_baseline",timeoutTicks=300)
 public static void aFedRegisteredWolfWithoutACartDoesNotCloseTheCourierPosts(GameTestHelper h){
  var t=town(h);h.startSequence().thenWaitUntil(()->h.assertTrue(t.l.isPositionEntityTicking(t.porter.blockPosition())&&t.l.isPositionEntityTicking(t.wolf.blockPosition()),"Both real body chunks are entity ticking")).thenExecute(()->{h.assertTrue(t.l.getEntity(t.porter.getUUID())==null&&t.l.getEntity(t.wolf.getUUID())==null,"No competing canonical bodies before synchronous admission");SettlementData.get(t.l.getServer()).add(t.e);h.assertTrue(t.l.addFreshEntity(t.porter)&&t.l.getEntity(t.porter.getUUID())==t.porter&&t.l.addFreshEntity(t.wolf)&&t.l.getEntity(t.wolf.getUUID())==t.wolf,"Actual canonical courier and wolf bodies are added");}).thenWaitUntil(()->h.assertTrue(t.porter.tickCount>2&&t.wolf.tickCount>0,"Both actual bodies tick")).thenExecute(()->{try{
   VillageDogs.provide(VillageWolves.DOGS);h.assertTrue(VillageWolves.eat(t.l,t.e,t.wolf)&&LogisticsRoutes.chest(t.l,t.e,t.kennel).countItem(Items.BEEF)==0&&VillageWolves.fed(t.l,t.wolf)&&VillageDogs.available(t.l,t.e).contains(t.wolf.getUUID()),"The actual registered free wolf is fed by one physically paid finite meal");h.assertTrue(BuildingLevels.level(t.l,t.e,t.store)==6&&CartWolves.alone(t.l,t.e,t.store)&&WarehouseCarts.have(t.l,t.store.id())==0&&WarehouseCarts.carts(t.l,t.store).isEmpty(),"A working warehouse VI and logistics gate stand with no cart item, record or entity");
   Warehouses.tick(t.l,t.e,20);Population.assign(t.e,1);var r=t.s.resident(t.porter.getUUID());com.mojang.logging.LogUtils.getLogger().info("ZIMBOVILLAGERS_WAREHOUSE_RELIEF baseline=true carts={} wolfTrips={} freeFedWolves={} relieved={} slots={} porterProfession={}",WarehouseCarts.have(t.l,t.store.id()),WarehouseTrips.wolves(t.l,t.e,t.store),VillageDogs.available(t.l,t.e).size(),CartWolves.relieved(t.s.id()),Population.slots(t.s,t.store),r.profession());h.assertTrue(Population.slots(t.s,t.store)==2&&r.profession()==Profession.PORTER&&t.s.workplace(r.id()).id().equals(t.store.id()),"No registered usable cart or running wolf delivery: the documented two courier posts and existing assignment must remain");
  }finally{t.close();}}).thenSucceed();
 }

 private static boolean readyChunks(Town t){var missing=t.held.stream().filter(c->!t.l.isPositionEntityTicking(new BlockPos(c.x*16,110,c.z*16))).toList();boolean bay=t.l.areEntitiesLoaded(net.minecraft.world.level.ChunkPos.asLong(WarehouseStore.at(t.e,t.store,WarehouseStore.B1)));if((!missing.isEmpty()||!bay)&&t.l.getServer().getTickCount()%100==0)com.mojang.logging.LogUtils.getLogger().info("ZIMBOVILLAGERS_WAREHOUSE_RELIEF sceneWaiting=true center={} bayLoaded={} missing={} currentlyForced={}",t.e.center(),bay,missing,t.l.getForcedChunks());return missing.isEmpty()&&bay;}
 static net.minecraft.gametest.framework.GameTestSequence admitted(GameTestHelper h,Town t){return admitted(h,t,-1);}
 static net.minecraft.gametest.framework.GameTestSequence admitted(GameTestHelper h,Town t,int parity){
  return h.startSequence().thenWaitUntil(()->h.assertTrue(readyChunks(t),"All forced fixture chunks and the actual cart bay are entity ticking")).thenWaitUntil(()->h.assertTrue(t.l.isPositionEntityTicking(t.porter.blockPosition())&&t.l.isPositionEntityTicking(t.wolf.blockPosition()),"Body chunks tick before admission")).thenWaitUntil(()->h.assertTrue(parity<0||Math.floorMod(t.l.getServer().getTickCount()+t.wolf.getId(),2)==parity,"Controlled initial admission selects ordinary goal body parity before add")).thenExecute(()->{h.assertTrue(t.l.getEntity(t.porter.getUUID())==null&&t.l.getEntity(t.wolf.getUUID())==null,"No competing bodies");SettlementData.get(t.l.getServer()).add(t.e);h.assertTrue(t.l.addFreshEntity(t.porter)&&t.l.getEntity(t.porter.getUUID())==t.porter&&t.l.addFreshEntity(t.wolf)&&t.l.getEntity(t.wolf.getUUID())==t.wolf,"Canonical admitted bodies");}).thenWaitUntil(()->h.assertTrue(t.porter.tickCount>2&&t.wolf.tickCount>0,"Bodies tick")).thenExecute(()->{VillageDogs.provide(VillageWolves.DOGS);h.assertTrue(VillageWolves.eat(t.l,t.e,t.wolf)&&LogisticsRoutes.chest(t.l,t.e,t.kennel).countItem(Items.BEEF)==0,"Finite meal paid");});
 }
 static CartEntity cart(GameTestHelper h,Town t){WarehouseCarts.ensure(t.l,t.e,t.store);var carts=WarehouseCarts.carts(t.l,t.store);h.assertTrue(carts.size()==1&&LogisticsRoutes.chest(t.l,t.e,t.store).countItem(VillageAstra.CART_ITEM.get())==0,"Exactly one registered real cart consumes the finite cart item");var c=carts.get(0);h.assertTrue(org.villageastra.persistence.WorldJournal.inspectCommitted(t.l,Settlement.childId(t.store.id(),"cart/"+c.getUUID()))!=null,"Cart payment is committed");return c;}
 private static void posted(GameTestHelper h,Town t,String reason){h.assertTrue(!CartWolves.relieved(t.s.id())&&Population.slots(t.s,t.store)==2,reason);}
 @GameTest(template="empty",batch="warehouse_relief",timeoutTicks=400)
 public static void onlyUsablePaidTransportAndAnAvailableVillageWolfRelievePosts(GameTestHelper h){
  var t=town(h);admitted(h,t).thenExecute(()->{try{
   var stock=LogisticsRoutes.chest(t.l,t.e,t.store);stock.setItem(0,new ItemStack(VillageAstra.CART_ITEM.get(),1));var c=cart(h,t);
   // No demand: a ready service need not manufacture a fictitious trip just to establish availability.
   Warehouses.tick(t.l,t.e,20);h.assertTrue(CartWolves.relieved(t.s.id())&&WarehouseTrips.wolves(t.l,t.e,t.store)==0,"Idle paid cart and ready fed wolf form an available service without fictitious demand");
   t.wolf.setOrderedToSit(true);Warehouses.tick(t.l,t.e,20);posted(h,t,"Sitting wolf cannot replace the courier");t.wolf.setOrderedToSit(false);
   h.assertTrue(VillageDogs.harness(t.l,t.e,t.wolf.getUUID(),c),"Actual village wolf harness is acquired");Warehouses.tick(t.l,t.e,20);posted(h,t,"Busy wolf/cart without a warehouse trip is no available service");VillageWolves.releaseDog(t.l,t.wolf.getUUID());
   c.travel(UUID.randomUUID(),0);Warehouses.tick(t.l,t.e,20);posted(h,t,"A travelling cart belonging to another active work cannot replace courier posts");c.travel(null,0);
   c.puller(UUID.randomUUID());Warehouses.tick(t.l,t.e,20);posted(h,t,"Occupied cart cannot be picked up");c.puller(null);
   // A real stranded cart is precisely the existing recovery pickup, not just a record promising a missing body.
   c.moveTo(t.e.center().getX()+64.5,t.e.center().getY(),t.e.center().getZ()+18.5);h.assertTrue(WarehouseCarts.stranded(t.l,t.e,t.store)==c,"Loaded real cart is recoverable outside the home radius");t.wolf.setOrderedToSit(true);Warehouses.tick(t.l,t.e,20);posted(h,t,"Stranded cart still needs an available village wolf");t.wolf.setOrderedToSit(false);
   // Test the relief predicate before the normal tick converts this pickup into an active fetch.
   try{var m=CartWolves.class.getDeclaredMethod("update",ServerLevel.class,SettlementData.Entry.class,Settlement.Building.class);m.setAccessible(true);m.invoke(null,t.l,t.e,t.store);}catch(ReflectiveOperationException ex){throw new IllegalStateException(ex);}posted(h,t,"A distant stranded cart is not yet working replacement transport");Warehouses.tick(t.l,t.e,20);var pickup=WarehouseTrips.inspect(t.l,t.wolf.getUUID());h.assertTrue(WarehouseTrips.active(pickup)&&pickup.getString("stage").equals("fetch")&&pickup.getUUID("cart").equals(c.getUUID())&&c.travelling(),"The same loaded stranded cart is actually claimed by the standard wolf pickup");WarehouseTrips.release(t.l,t.wolf.getUUID());
   c.remove(net.minecraft.world.entity.Entity.RemovalReason.UNLOADED_TO_CHUNK);h.assertTrue(WarehouseCarts.have(t.l,t.store.id())==1&&WarehouseCarts.carts(t.l,t.store).isEmpty(),"Persistent placed registry remains but its body is absent");Warehouses.tick(t.l,t.e,20);posted(h,t,"A registry entry without a loaded cart body cannot relieve the courier");Population.assign(t.e,1);h.assertTrue(t.s.resident(t.porter.getUUID()).profession()==Profession.PORTER,"The existing courier stays assigned when replacement disappears");
  }finally{t.close();}}).thenSucceed();
 }
 static void nativeRouteReady(GameTestHelper h,Town t){
  var target=BuildingPlacement.at(t.e,t.mine,BuildingBlueprints.doorX(t.mine.type()),1,-2);var range=t.wolf.getAttribute(net.minecraft.world.entity.ai.attributes.Attributes.FOLLOW_RANGE);var lent=UUID.fromString("d6c9c72b-9029-421f-b38b-f4e11b1d2f41");t.wolf.getNavigation().setMaxVisitedNodesMultiplier(4F);range.addTransientModifier(new net.minecraft.world.entity.ai.attributes.AttributeModifier(lent,"Fixture existing kennel path range",32,net.minecraft.world.entity.ai.attributes.AttributeModifier.Operation.ADDITION));try{var path=t.wolf.getNavigation().createPath(target,1);h.assertTrue(t.wolf.onGround()&&path!=null&&path.canReach(),"Canonical grounded initial hitch admission has a real reachable native path to the first actual stop");com.mojang.logging.LogUtils.getLogger().info("ZIMBOVILLAGERS_WAREHOUSE_RELIEF initialNativeRoute=true wolf={} ground={} target={} nodes={} canReach={}",t.wolf.position(),t.wolf.onGround(),target,path.getNodeCount(),path.canReach());}finally{range.removeModifier(lent);}
 }
 private static void physicalTick(Town t){
  var before=WarehouseTrips.inspect(t.l,t.wolf.getUUID()).copy();var cart=before.hasUUID("cart")?t.l.getEntity(before.getUUID("cart")):null;var cp=cart==null?null:cart.blockPosition();boolean blocked=cart instanceof CartEntity c&&c.blocked();var sent=VillageWolves.sentTo(t.wolf);
  if(t.wolf.tickCount%100<20){var p=t.wolf.getNavigation().getPath();com.mojang.logging.LogUtils.getLogger().info("ZIMBOVILLAGERS_WAREHOUSE_RELIEF routeTrace=true noAI={} stage={} ground={} bodyTicks={} wolf={} sent={} target={} reach={} nodes={} goals={} cart={} away={}",t.wolf.isNoAi(),before.getString("stage"),t.wolf.onGround(),t.wolf.tickCount,t.wolf.position(),sent,p==null?null:p.getTarget(),p!=null&&p.canReach(),p==null?null:p.getNextNodeIndex()+"/"+p.getNodeCount()+"@"+(p.isDone()?"done":p.getNextNodePos()),t.wolf.goalSelector.getRunningGoals().map(g->g.getGoal().getClass().getSimpleName()).toList(),cp,before.getInt("away"));}
  Warehouses.tick(t.l,t.e,20);var after=WarehouseTrips.inspect(t.l,t.wolf.getUUID());if(before.hasUUID("cart")&&WarehouseTrips.active(after)&&!after.hasUUID("cart"))com.mojang.logging.LogUtils.getLogger().info("ZIMBOVILLAGERS_WAREHOUSE_RELIEF nativeCartLoss=true beforeStage={} beforeAway={} beforeBlocked={} actualCartBlocked={} actualWolf={} actualCart={} sent={}",before.getString("stage"),before.getInt("away"),before.getInt("blocked"),blocked,t.wolf.position(),cp,sent);
 }
 @GameTest(template="empty",batch="warehouse_relief_physical",timeoutTicks=2400)
 public static void aPaidWolfCartPhysicallyCarriesAndReplaysWithoutDuplicatingItsLoad(GameTestHelper h){
  var t=town(h,true,true);boolean[] taken={false},finished={false},integrity={true};UUID[] trip={null};int[] callbacks={0};double[] walked={0};net.minecraft.world.phys.Vec3[] last={t.wolf.position()};float health=t.wolf.getHealth();
  admitted(h,t).thenExecute(()->{t.wolf.goalSelector.removeAllGoals(g->true);t.wolf.targetSelector.removeAllGoals(g->true);t.wolf.setNoAi(false);}).thenWaitUntil(()->h.assertTrue(t.wolf.onGround(),"Actual native wolf body is grounded before route query")).thenExecute(()->{nativeRouteReady(h,t);LogisticsRoutes.chest(t.l,t.e,t.store).setItem(0,new ItemStack(VillageAstra.CART_ITEM.get(),1));var hitch=cart(h,t);LogisticsRoutes.chest(t.l,t.e,t.mine).setItem(0,new ItemStack(Items.COBBLESTONE,32));Warehouses.tick(t.l,t.e,20);Warehouses.tick(t.l,t.e,20);var initial=WarehouseTrips.inspect(t.l,t.wolf.getUUID());h.assertTrue(WarehouseTrips.active(initial)&&WarehouseTrips.custody(t.l,initial).isEmpty()&&LogisticsRoutes.chest(t.l,t.e,t.mine).countItem(Items.COBBLESTONE)==32&&(hitch.blockPosition().equals(VillageWolves.sentTo(t.wolf))||VillageDogs.near(t.l,t.e,t.wolf.getUUID(),hitch.blockPosition(),3)),"Before AI starts, normal unpaid fetch dispatch points to the actual paid cart and has taken no cargo");t.wolf.goalSelector.addGoal(0,new WolfKennelGoal(t.wolf));t.wolf.goalSelector.addGoal(10,new net.minecraft.world.entity.ai.goal.Goal(){private int samples;@Override public boolean canUse(){return true;}@Override public void tick(){if(samples++<12)com.mojang.logging.LogUtils.getLogger().info("ZIMBOVILLAGERS_WAREHOUSE_RELIEF ordinaryGoalCadence=true serverTick={} entityId={} bodyTick={} mod10={} realGoalRunning={} realGoalNeedsEveryTick={}",t.l.getServer().getTickCount(),t.wolf.getId(),t.wolf.tickCount,t.wolf.tickCount%10,t.wolf.goalSelector.getRunningGoals().anyMatch(g->g.getGoal() instanceof WolfKennelGoal),t.wolf.goalSelector.getRunningGoals().filter(g->g.getGoal() instanceof WolfKennelGoal).allMatch(g->g.requiresUpdateEveryTick()));}});}).thenWaitUntil(()->{
   walked[0]+=t.wolf.position().distanceTo(last[0]);last[0]=t.wolf.position();if(callbacks[0]++%20==0){physicalTick(t);var x=WarehouseTrips.inspect(t.l,t.wolf.getUUID());if(WarehouseTrips.active(x)&&trip[0]==null)trip[0]=x.getUUID("id");if(!WarehouseTrips.custody(t.l,x).isEmpty()){taken[0]=true;WarehouseTrips.forget(t.l.getServer());integrity[0]&=WarehouseTrips.inspect(t.l,t.wolf.getUUID()).getUUID("id").equals(trip[0]);}if(taken[0]&&!WarehouseTrips.active(x)){finished[0]=true;}}
   h.assertTrue(finished[0],"Physical wolf trip has taken and returned finite cargo; stage="+WarehouseTrips.inspect(t.l,t.wolf.getUUID()).getString("stage")+" wolf="+t.wolf.blockPosition()+" sent="+VillageWolves.sentTo(t.wolf));
  }).thenExecute(()->{try{h.assertTrue(integrity[0],"Fresh signed trip reader always preserved exact paid trip and cargo");h.assertTrue(walked[0]>25&&t.wolf.tickCount>100&&t.wolf.getHealth()==health,"Actual native wolf walking preserves health");h.assertTrue(LogisticsRoutes.chest(t.l,t.e,t.mine).countItem(Items.COBBLESTONE)==0&&LogisticsRoutes.chest(t.l,t.e,t.store).countItem(Items.COBBLESTONE)==32,"Exactly 32 paid finite stones reach warehouse");WarehouseTrips.forget(t.l.getServer());for(int i=0;i<5;i++)Warehouses.tick(t.l,t.e,20);h.assertTrue(LogisticsRoutes.chest(t.l,t.e,t.store).countItem(Items.COBBLESTONE)==32&&LogisticsRoutes.chest(t.l,t.e,t.mine).countItem(Items.COBBLESTONE)==0,"Completed trip replay cannot duplicate its payment");t.wolf.setOrderedToSit(true);Warehouses.tick(t.l,t.e,20);posted(h,t,"Loss of the available replacement restores both warehouse posts after the real paid journey");var put=org.villageastra.persistence.WorldJournal.inspectCommitted(t.l,Settlement.childId(trip[0],"put/0"));var back=org.villageastra.persistence.WorldJournal.inspectCommitted(t.l,Settlement.childId(trip[0],"back/0"));h.assertTrue((put==null)!=(back==null)&&(put!=null?put:back).getLong("pos")==LogisticsRoutes.position(t.e,t.store).asLong(),"Physical journey has exactly one original receipt at this warehouse");com.mojang.logging.LogUtils.getLogger().info("ZIMBOVILLAGERS_WAREHOUSE_RELIEF physical=true bodyTicks={} walked={} finitePaid=32 finiteReturned=32 replay=5 receiptKind={}",t.wolf.tickCount,walked[0],put!=null?"put/0":"back/0");}finally{t.close();}}).thenSucceed();
 }

 @GameTest(template="empty",batch="warehouse_relief_custody",timeoutTicks=1800)
 public static void aRealPaidHumanParcelKeepsItsPostUntilPhysicalDelivery(GameTestHelper h){
  var t=town(h);boolean[] taken={false},finished={false},integrity={true};UUID[] job={null};int[] callbacks={0};float health=t.porter.getHealth();
  admitted(h,t).thenExecute(()->{LogisticsRoutes.chest(t.l,t.e,t.mine).setItem(0,new ItemStack(Items.COBBLESTONE,16));var route=LogisticsRoutes.choose(t.l,t.e,t.store,t.porter.blockPosition());h.assertTrue(route!=null&&route.source().id().equals(t.mine.id())&&route.destination().id().equals(t.store.id()),"Actual warehouse policy selects the finite mine output route");}).thenWaitUntil(()->{
   PorterWork.step(t.porter);var x=PorterWork.inspect(t.l,t.porter.getUUID());if(PorterWork.active(x)&&job[0]==null)job[0]=x.getUUID("id");
   if(!PorterWork.cargo(t.l,x).isEmpty()&&!taken[0]){taken[0]=true;integrity[0]&=PorterWork.cargo(t.l,x).getCount()==16&&LogisticsRoutes.chest(t.l,t.e,t.mine).countItem(Items.COBBLESTONE)==0;LogisticsRoutes.chest(t.l,t.e,t.store).setItem(0,new ItemStack(VillageAstra.CART_ITEM.get(),1));var replacement=cart(h,t);integrity[0]&=VillageDogs.available(t.l,t.e).contains(t.wolf.getUUID())&&VillageDogs.pickupReady(t.l,t.e,t.wolf.getUUID(),replacement);}
   if(taken[0]&&PorterWork.active(x)&&callbacks[0]++%20==0){Warehouses.tick(t.l,t.e,20);Population.assign(t.e,1);integrity[0]&=!CartWolves.relieved(t.s.id())&&Population.slots(t.s,t.store)==2&&t.s.resident(t.porter.getUUID()).profession()==Profession.PORTER&&t.s.workplace(t.porter.getUUID())!=null&&t.s.workplace(t.porter.getUUID()).id().equals(t.store.id())&&PorterWork.inspect(t.l,t.porter.getUUID()).getUUID("id").equals(job[0]);}
   if(taken[0]&&!PorterWork.active(x))finished[0]=true;h.assertTrue(finished[0],"The actual human courier physically finishes the paid route; stage="+x.getString("stage")+" paid="+taken[0]+" pos="+t.porter.blockPosition());
  }).thenExecute(()->{try{h.assertTrue(integrity[0],"Every paid waiting/walking frame preserved exact cargo, courier post and assignment");h.assertTrue(t.porter.tickCount>100&&t.porter.getHealth()==health&&LogisticsRoutes.chest(t.l,t.e,t.store).countItem(Items.COBBLESTONE)==16&&LogisticsRoutes.chest(t.l,t.e,t.mine).countItem(Items.COBBLESTONE)==0,"Finite paid cargo reaches warehouse exactly once without injury");Warehouses.tick(t.l,t.e,20);h.assertTrue(CartWolves.relieved(t.s.id())&&Population.slots(t.s,t.store)==0,"After actual put, empty-handed courier can be relieved by ready paid replacement");Population.assign(t.e,1);h.assertTrue(t.s.resident(t.porter.getUUID()).profession()!=Profession.PORTER,"Only the completed empty-handed courier is reassigned");com.mojang.logging.LogUtils.getLogger().info("ZIMBOVILLAGERS_WAREHOUSE_RELIEF human=true bodyTicks={} paid=16 delivered=16 exactParcelPreserved=true",t.porter.tickCount);}finally{t.close();}}).thenSucceed();
 }

 @GameTest(template="empty",batch="warehouse_relief_unloaded",timeoutTicks=400)
 public static void aWolfRegistryWithoutALoadedBodyDoesNotReplaceCouriers(GameTestHelper h){
  var t=town(h);admitted(h,t).thenExecute(()->{try{LogisticsRoutes.chest(t.l,t.e,t.store).setItem(0,new ItemStack(VillageAstra.CART_ITEM.get(),1));var c=cart(h,t);Warehouses.tick(t.l,t.e,20);h.assertTrue(CartWolves.relieved(t.s.id()),"Actual ready paid service relieves posts first");t.wolf.remove(net.minecraft.world.entity.Entity.RemovalReason.UNLOADED_TO_CHUNK);h.assertTrue(VillageWolves.wolves(t.l,t.e).contains(t.wolf.getUUID())&&VillageDogs.available(t.l,t.e).isEmpty()&&WarehouseCarts.free(t.l,t.e,t.store,null)==c,"Wolf registry remains while its body is unloaded; real cart stays available");Warehouses.tick(t.l,t.e,20);posted(h,t,"Registry without loaded available wolf cannot replace courier posts");Population.assign(t.e,1);h.assertTrue(t.s.resident(t.porter.getUUID()).profession()==Profession.PORTER,"Courier assignment remains when the wolf body leaves");}finally{t.close();}}).thenSucceed();
 }

 @GameTest(template="empty",batch="warehouse_relief_fetch_baseline",timeoutTicks=400)
 public static void aDistantWolfFetchDoesNotClosePostsBeforeTheHitchIsReached(GameTestHelper h){
  var t=town(h,false);admitted(h,t).thenExecute(()->{try{LogisticsRoutes.chest(t.l,t.e,t.store).setItem(0,new ItemStack(VillageAstra.CART_ITEM.get(),1));var c=cart(h,t);h.assertTrue(!VillageDogs.near(t.l,t.e,t.wolf.getUUID(),c.blockPosition(),3),"Real fed village wolf is physically distant from its paid cart");LogisticsRoutes.chest(t.l,t.e,t.mine).setItem(0,new ItemStack(Items.COBBLESTONE,32));Warehouses.tick(t.l,t.e,20);var x=WarehouseTrips.inspect(t.l,t.wolf.getUUID());h.assertTrue(WarehouseTrips.active(x)&&x.getString("stage").equals("fetch")&&WarehouseTrips.custody(t.l,x).isEmpty(),"Standard unpaid fetch starts before wolf reaches the hitch");com.mojang.logging.LogUtils.getLogger().info("ZIMBOVILLAGERS_WAREHOUSE_RELIEF fetchBaseline=true stage={} near={} relieved={} slots={}",x.getString("stage"),VillageDogs.near(t.l,t.e,t.wolf.getUUID(),c.blockPosition(),3),CartWolves.relieved(t.s.id()),Population.slots(t.s,t.store));posted(h,t,"An unpaid distant fetch is not yet replacement service: courier posts remain");}finally{WarehouseTrips.release(t.l,t.wolf.getUUID());t.close();}}).thenSucceed();
 }

 @GameTest(template="empty",batch="warehouse_relief_walled",timeoutTicks=500)
 public static void anUnpaidWolfBehindAWallKeepsTheHumanService(GameTestHelper h){
  var t=town(h,false);boolean[] integrity={true};int[] frames={0};
  admitted(h,t).thenExecute(()->{LogisticsRoutes.chest(t.l,t.e,t.store).setItem(0,new ItemStack(VillageAstra.CART_ITEM.get(),1));cart(h,t);LogisticsRoutes.chest(t.l,t.e,t.mine).setItem(0,new ItemStack(Items.COBBLESTONE,32));var c=t.e.center();for(var p:BlockPos.betweenClosed(c.offset(38,0,0),c.offset(42,4,4)))if(p.getX()==c.getX()+38||p.getX()==c.getX()+42||p.getZ()==c.getZ()||p.getZ()==c.getZ()+4||p.getY()==c.getY()+4)t.l.setBlock(p,Blocks.STONE.defaultBlockState(),2);t.wolf.setNoAi(false);t.wolf.goalSelector.removeAllGoals(g->!(g instanceof WolfKennelGoal));t.wolf.targetSelector.removeAllGoals(g->true);}).thenWaitUntil(()->{if(frames[0]++%20==0){Warehouses.tick(t.l,t.e,20);var x=WarehouseTrips.inspect(t.l,t.wolf.getUUID());integrity[0]&=WarehouseTrips.active(x)&&x.getString("stage").equals("fetch")&&WarehouseTrips.custody(t.l,x).isEmpty()&&!CartWolves.relieved(t.s.id())&&Population.slots(t.s,t.store)==2;}h.assertTrue(frames[0]>=120,"Observe real blocked navigation for 120 frames");}).thenExecute(()->{try{h.assertTrue(integrity[0]&&t.wolf.tickCount>=120&&LogisticsRoutes.chest(t.l,t.e,t.mine).countItem(Items.COBBLESTONE)==32,"Unpaid fetch behind a real wall never replaced courier service or withdrew cargo");}finally{WarehouseTrips.release(t.l,t.wolf.getUUID());t.close();}}).thenSucceed();
 }
 @GameTest(template="empty",batch="warehouse_relief_stranded_ready",timeoutTicks=400)
 public static void aReadyWolfAtItsActualStrandedCartProvidesTheRecoveryService(GameTestHelper h){
  var t=town(h,false);t.wolf.moveTo(t.e.center().getX()+64.5,110,t.e.center().getZ()+18.5);
  admitted(h,t).thenExecute(()->{try{LogisticsRoutes.chest(t.l,t.e,t.store).setItem(0,new ItemStack(VillageAstra.CART_ITEM.get(),1));var c=cart(h,t);c.moveTo(t.e.center().getX()+65.5,110,t.e.center().getZ()+18.5);h.assertTrue(WarehouseCarts.stranded(t.l,t.e,t.store)==c&&VillageDogs.available(t.l,t.e).contains(t.wolf.getUUID())&&VillageDogs.near(t.l,t.e,t.wolf.getUUID(),c.blockPosition(),3),"Actual ready village wolf is already at the loaded recoverable stranded cart");Warehouses.tick(t.l,t.e,20);h.assertTrue(CartWolves.relieved(t.s.id())&&WarehouseTrips.inspect(t.l,t.wolf.getUUID()).getString("stage").equals("fetch")&&c.travelling(),"The confirmed actual hitch provides recovery service without losing the paid cart");}finally{WarehouseTrips.release(t.l,t.wolf.getUUID());t.close();}}).thenSucceed();
 }
 private static void observe(Town t){try{var m=CartWolves.class.getDeclaredMethod("update",ServerLevel.class,SettlementData.Entry.class,Settlement.Building.class);m.setAccessible(true);m.invoke(null,t.l,t.e,t.store);}catch(ReflectiveOperationException ex){throw new IllegalStateException(ex);}}
 @GameTest(template="empty",batch="warehouse_relief_current_eligibility",timeoutTicks=400)
 public static void anUnpaidFetchRechecksTheCurrentWolfAndAllowsOnlyItsOwnBusyHitch(GameTestHelper h){
  var t=town(h);admitted(h,t).thenExecute(()->{try{LogisticsRoutes.chest(t.l,t.e,t.store).setItem(0,new ItemStack(VillageAstra.CART_ITEM.get(),1));var c=cart(h,t);LogisticsRoutes.chest(t.l,t.e,t.mine).setItem(0,new ItemStack(Items.COBBLESTONE,32));Warehouses.tick(t.l,t.e,20);h.assertTrue(WarehouseTrips.inspect(t.l,t.wolf.getUUID()).getString("stage").equals("fetch")&&VillageDogs.available(t.l,t.e).isEmpty()&&VillageDogs.pickupReady(t.l,t.e,t.wolf.getUUID(),c)&&CartWolves.relieved(t.s.id()),"Current own pending harness is eligible without incorrectly requiring free source availability");t.wolf.setOrderedToSit(true);observe(t);posted(h,t,"A wolf sitting after allocation is not current replacement service");t.wolf.setOrderedToSit(false);var fed=t.wolf.getPersistentData().getLong(VillageWolves.FED);t.wolf.getPersistentData().remove(VillageWolves.FED);observe(t);posted(h,t,"A wolf whose paid feeding eligibility no longer holds cannot replace couriers");t.wolf.getPersistentData().putLong(VillageWolves.FED,fed);var village=VillageWolves.village(t.wolf);t.wolf.getPersistentData().putUUID(VillageWolves.TAG,UUID.randomUUID());observe(t);posted(h,t,"Changed village identity cannot supply this warehouse service");t.wolf.getPersistentData().putUUID(VillageWolves.TAG,village);VillageDogs.follow(t.l,t.e,t.wolf.getUUID(),t.porter);observe(t);posted(h,t,"A simultaneous courier follower reservation is not this wolf's own hitch");VillageWolves.releaseDog(t.l,t.wolf.getUUID());observe(t);h.assertTrue(CartWolves.relieved(t.s.id())&&VillageDogs.pickupReady(t.l,t.e,t.wolf.getUUID(),c),"Absent in-memory busy marks after release/reload do not reject the valid saved fetch");h.assertTrue(LogisticsRoutes.chest(t.l,t.e,t.mine).countItem(Items.COBBLESTONE)==32&&WarehouseTrips.custody(t.l,WarehouseTrips.inspect(t.l,t.wolf.getUUID())).isEmpty(),"Read-only eligibility observations have not withdrawn or moved any finite cargo");}finally{WarehouseTrips.release(t.l,t.wolf.getUUID());t.close();}}).thenSucceed();
 }

 @GameTest(template="empty",batch="warehouse_relief_paid_recovery",timeoutTicks=1800)
 public static void aReachablePaidWolfCheckpointPhysicallyReturnsToItsWarehouseAndReplaysExactlyOnce(GameTestHelper h){
  var t=town(h,true,true);CompoundTag[] paid={null};boolean[] integrity={true},finished={false};int[] frames={0};float hp=t.wolf.getHealth();
  admitted(h,t).thenExecute(()->{t.wolf.goalSelector.removeAllGoals(g->true);t.wolf.targetSelector.removeAllGoals(g->true);t.wolf.setNoAi(false);}).thenWaitUntil(()->h.assertTrue(t.wolf.onGround(),"Actual native wolf body is grounded before route query")).thenExecute(()->{nativeRouteReady(h,t);LogisticsRoutes.chest(t.l,t.e,t.store).setItem(0,new ItemStack(VillageAstra.CART_ITEM.get(),1));var hitch=cart(h,t);LogisticsRoutes.chest(t.l,t.e,t.mine).setItem(0,new ItemStack(Items.COBBLESTONE,32));Warehouses.tick(t.l,t.e,20);Warehouses.tick(t.l,t.e,20);var initial=WarehouseTrips.inspect(t.l,t.wolf.getUUID());h.assertTrue(WarehouseTrips.active(initial)&&WarehouseTrips.custody(t.l,initial).isEmpty()&&LogisticsRoutes.chest(t.l,t.e,t.mine).countItem(Items.COBBLESTONE)==32&&(hitch.blockPosition().equals(VillageWolves.sentTo(t.wolf))||VillageDogs.near(t.l,t.e,t.wolf.getUUID(),hitch.blockPosition(),3)),"Before AI starts, normal unpaid fetch dispatch points to the actual paid cart and has taken no cargo");t.wolf.goalSelector.addGoal(0,new WolfKennelGoal(t.wolf));t.wolf.goalSelector.addGoal(10,new net.minecraft.world.entity.ai.goal.Goal(){private int samples;@Override public boolean canUse(){return true;}@Override public void tick(){if(samples++<12)com.mojang.logging.LogUtils.getLogger().info("ZIMBOVILLAGERS_WAREHOUSE_RELIEF ordinaryGoalCadence=true serverTick={} entityId={} bodyTick={} mod10={} realGoalRunning={} realGoalNeedsEveryTick={}",t.l.getServer().getTickCount(),t.wolf.getId(),t.wolf.tickCount,t.wolf.tickCount%10,t.wolf.goalSelector.getRunningGoals().anyMatch(g->g.getGoal() instanceof WolfKennelGoal),t.wolf.goalSelector.getRunningGoals().filter(g->g.getGoal() instanceof WolfKennelGoal).allMatch(g->g.requiresUpdateEveryTick()));}});}).thenWaitUntil(()->{
   if(frames[0]++%20==0){physicalTick(t);var x=WarehouseTrips.inspect(t.l,t.wolf.getUUID());if(paid[0]==null&&!WarehouseTrips.custody(t.l,x).isEmpty()){paid[0]=x.copy();integrity[0]&=!x.getString("stage").equals("fetch")&&WarehouseTrips.custody(t.l,x).size()==1&&WarehouseTrips.custody(t.l,x).get(0).getCount()==32;WarehouseTrips.forget(t.l.getServer());integrity[0]&=WarehouseTrips.inspect(t.l,t.wolf.getUUID()).equals(paid[0]);}if(paid[0]!=null&&!WarehouseTrips.active(x)){finished[0]=true;t.wolf.setNoAi(true);}}
   h.assertTrue(finished[0],"Native path first establishes actual paid take and only then tests checkpoint recovery; checkpoint="+(paid[0]!=null)+" stage="+WarehouseTrips.inspect(t.l,t.wolf.getUUID()).getString("stage")+" pos="+t.wolf.blockPosition());
  }).thenExecute(()->{try{h.assertTrue(integrity[0]&&paid[0]!=null&&t.wolf.tickCount>100&&t.wolf.getHealth()==hp,"Only a reachable actual paid non-fetch checkpoint was reloaded, with native walking and unchanged health");var id=paid[0].getUUID("id");var putId=Settlement.childId(id,"put/0");var backId=Settlement.childId(id,"back/0");var put=org.villageastra.persistence.WorldJournal.inspectCommitted(t.l,putId);var back=org.villageastra.persistence.WorldJournal.inspectCommitted(t.l,backId);var receipt=put!=null?put:back;var receiptId=put!=null?putId:backId;h.assertTrue((put==null)!=(back==null)&&receipt.getLong("pos")==LogisticsRoutes.position(t.e,t.store).asLong(),"Exactly one original put/back receipt returns all paid cargo at this warehouse address");h.assertTrue(Arrays.equals(WarehouseTrips.audit(t.l,paid[0]),new int[]{32,32,0})&&LogisticsRoutes.chest(t.l,t.e,t.store).countItem(Items.COBBLESTONE)==32&&LogisticsRoutes.chest(t.l,t.e,t.mine).countItem(Items.COBBLESTONE)==0,"All 32 actually paid stones reach this warehouse, with no cargo left or lost");var path=t.l.getServer().getWorldPath(net.minecraft.world.level.storage.LevelResource.ROOT).resolve("data/astra-haul/"+t.wolf.getUUID()+".bin");org.villageastra.persistence.NbtRecord.write(path,paid[0]);WarehouseTrips.forget(t.l.getServer());for(int i=0;i<5;i++)Warehouses.tick(t.l,t.e,20);h.assertTrue(!WarehouseTrips.active(WarehouseTrips.inspect(t.l,t.wolf.getUUID()))&&Arrays.equals(WarehouseTrips.audit(t.l,paid[0]),new int[]{32,32,0})&&LogisticsRoutes.chest(t.l,t.e,t.store).countItem(Items.COBBLESTONE)==32&&LogisticsRoutes.chest(t.l,t.e,t.mine).countItem(Items.COBBLESTONE)==0,"Restoring the reachable paid signed checkpoint replays the exact original deposit once and never duplicates");h.assertTrue(receipt.equals(org.villageastra.persistence.WorldJournal.inspectCommitted(t.l,receiptId))&&org.villageastra.persistence.WorldJournal.inspectCommitted(t.l,put!=null?backId:putId)==null,"Replay retains the same exact signed warehouse deposit and creates no alternate deposit receipt");com.mojang.logging.LogUtils.getLogger().info("ZIMBOVILLAGERS_WAREHOUSE_RELIEF reachableRecovery=true checkpointStage={} bodyTicks={} paid=32 exactWarehouseReceipt=32 receiptKind={} replay=5 audit={}",paid[0].getString("stage"),t.wolf.tickCount,put!=null?"put/0":"back/0",Arrays.toString(WarehouseTrips.audit(t.l,paid[0])));}finally{t.close();}}).thenSucceed();
 }
}
