package org.villageastra.domain;
import java.util.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
class ElectionRollTest {
 @Test void sameTickTiesUseAchievementNotUuidOrRegistration(){var r=new ElectionRoll();var first=new UUID(9,9);var second=new UUID(0,0);r.gift(first,ElectionRoll.MINIMUM+72);r.gift(second,ElectionRoll.MINIMUM+72);r.candidate(second,true);r.candidate(first,true);assertEquals(first,r.winner().orElseThrow().player());var restored=ElectionRoll.restore(r.sequence(),r.lastDecay(),r.accounts());assertEquals(first,restored.winner().orElseThrow().player());}
 @Test void fallingBelowThresholdLosesThatSeniority(){var r=new ElectionRoll();var a=UUID.randomUUID();var b=UUID.randomUUID();r.gift(a,ElectionRoll.MINIMUM+72);r.gift(b,ElectionRoll.MINIMUM+72);r.candidate(a,true);r.candidate(b,true);r.theft(a,1);r.gift(a,1);assertEquals(b,r.winner().orElseThrow().player());r.theft(a,1);r.theft(b,1);assertEquals(a,r.winner().orElseThrow().player(),"Earlier uninterrupted achievement of 199 survives falling from 200");}
 @Test void exactScoresAboveDoublePrecisionRemainDistinct(){var r=new ElectionRoll();var a=UUID.randomUUID();var b=UUID.randomUUID();r.gift(a,9007199254740992L);r.gift(b,9007199254740993L);r.candidate(a,true);r.candidate(b,true);assertEquals(b,r.winner().orElseThrow().player());}
 @Test void decayIsActiveTimeOnlyAndNeverPushesPositiveBalanceBelowZero(){var r=new ElectionRoll();var a=UUID.randomUUID();r.gift(a,ElectionRoll.MINIMUM+1);r.candidate(a,true);assertFalse(r.decay(23999));assertTrue(r.decay(24000));assertEquals(ElectionRoll.MINIMUM,r.account(a).score());assertTrue(r.winner().isPresent());assertFalse(r.decay(24000));r.decay(48000);assertTrue(r.winner().isEmpty());r.decay(24000*(ElectionRoll.MINIMUM+1000));assertEquals(0,r.account(a).score());assertTrue(r.account(a).bands().isEmpty());}
 @Test void corruptedOrDuplicateAchievementHistoryIsRejected(){var id=UUID.randomUUID();assertThrows(IllegalArgumentException.class,()->ElectionRoll.restore(2,0,List.of(new ElectionRoll.Account(id,200,0,0,true,List.of(new ElectionRoll.Band(1,199,1))))));var r=new ElectionRoll();r.gift(id,200);var a=r.account(id);assertThrows(IllegalArgumentException.class,()->ElectionRoll.restore(r.sequence(),0,List.of(a,a)));}
 @Test void largestExactBalanceSurvivesAndOverflowDoesNotMutateIt(){var r=new ElectionRoll();var id=UUID.randomUUID();r.gift(id,Long.MAX_VALUE);var restored=ElectionRoll.restore(r.sequence(),0,r.accounts());assertEquals(Long.MAX_VALUE,restored.account(id).score());assertThrows(ArithmeticException.class,()->restored.gift(id,1));assertEquals(Long.MAX_VALUE,restored.account(id).score());assertEquals(1,restored.sequence());}
 @Test void npcSuccessionPreservesPeopleHomesAndOrders(){var s=Settlement.initial(UUID.randomUUID());var mayor=s.residents().stream().filter(r->r.profession()==Profession.MAYOR).findFirst().orElseThrow();var player=UUID.randomUUID();var project=UUID.randomUUID();s.appointPlayerMayor(player);var g=s.governance();long epoch=g.epoch();assertTrue(g.setPaused(player,epoch,0,project,true));assertTrue(s.appointNpcMayor());assertEquals(Profession.MAYOR,mayor.profession());assertNull(g.playerMayor());assertFalse(g.canManage(player,epoch));assertTrue(g.paused(project));mayor.die();assertTrue(s.appointNpcMayor());assertEquals(1,s.residents().stream().filter(r->r.profession()==Profession.MAYOR).count());assertEquals(6,s.residents().size());assertEquals(3,s.homes().size());}
}
